'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

'
'This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
'
Namespace KniffelPutScore
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="KniffelScore", [Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class KniffelScore
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private HighScoreField As Integer
        
        Private TotalField As Integer
        
        Private GamesField As Integer
        
        Private PlayerField As String
        
        Private PicUrlField As String
        
        Private PlaceField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property HighScore() As Integer
            Get
                Return Me.HighScoreField
            End Get
            Set
                If (Me.HighScoreField.Equals(value) <> true) Then
                    Me.HighScoreField = value
                    Me.RaisePropertyChanged("HighScore")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Total() As Integer
            Get
                Return Me.TotalField
            End Get
            Set
                If (Me.TotalField.Equals(value) <> true) Then
                    Me.TotalField = value
                    Me.RaisePropertyChanged("Total")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property Games() As Integer
            Get
                Return Me.GamesField
            End Get
            Set
                If (Me.GamesField.Equals(value) <> true) Then
                    Me.GamesField = value
                    Me.RaisePropertyChanged("Games")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Player() As String
            Get
                Return Me.PlayerField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PlayerField, value) <> true) Then
                    Me.PlayerField = value
                    Me.RaisePropertyChanged("Player")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Property PicUrl() As String
            Get
                Return Me.PicUrlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PicUrlField, value) <> true) Then
                    Me.PicUrlField = value
                    Me.RaisePropertyChanged("PicUrl")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property Place() As Integer
            Get
                Return Me.PlaceField
            End Get
            Set
                If (Me.PlaceField.Equals(value) <> true) Then
                    Me.PlaceField = value
                    Me.RaisePropertyChanged("Place")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.sanet.com/", ConfigurationName:="KniffelPutScore.KniffelServiceSoap")>  _
    Public Interface KniffelServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://www.sanet.com/PutScore", ReplyAction:="*")>  _
        Function BeginPutScore(ByVal request As KniffelPutScore.PutScoreRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndPutScore(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://www.sanet.com/PutScoreIntoTable", ReplyAction:="*")>  _
        Function BeginPutScoreIntoTable(ByVal request As KniffelPutScore.PutScoreIntoTableRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndPutScoreIntoTable(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreIntoTableResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://www.sanet.com/PutScoreIntoTableWithPic", ReplyAction:="*")>  _
        Function BeginPutScoreIntoTableWithPic(ByVal request As KniffelPutScore.PutScoreIntoTableWithPicRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndPutScoreIntoTableWithPic(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreIntoTableWithPicResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://www.sanet.com/GetTopPlayers", ReplyAction:="*")>  _
        Function BeginGetTopPlayers(ByVal request As KniffelPutScore.GetTopPlayersRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetTopPlayers(ByVal result As System.IAsyncResult) As KniffelPutScore.GetTopPlayersResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://www.sanet.com/GetChempion", ReplyAction:="*")>  _
        Function BeginGetChempion(ByVal request As KniffelPutScore.GetChempionRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndGetChempion(ByVal result As System.IAsyncResult) As KniffelPutScore.GetChempionResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutScoreRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutScore", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.PutScoreRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.PutScoreRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class PutScoreRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Pass As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Score As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserName As String, ByVal Pass As String, ByVal Score As String)
            MyBase.New
            Me.UserName = UserName
            Me.Pass = Pass
            Me.Score = Score
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutScoreResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutScoreResponse", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.PutScoreResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.PutScoreResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class PutScoreResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public PutScoreResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PutScoreResult As Boolean)
            MyBase.New
            Me.PutScoreResult = PutScoreResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutScoreIntoTableRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutScoreIntoTable", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.PutScoreIntoTableRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.PutScoreIntoTableRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class PutScoreIntoTableRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Pass As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Score As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public table As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal table As String)
            MyBase.New
            Me.UserName = UserName
            Me.Pass = Pass
            Me.Score = Score
            Me.table = table
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutScoreIntoTableResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutScoreIntoTableResponse", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.PutScoreIntoTableResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.PutScoreIntoTableResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class PutScoreIntoTableResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public PutScoreIntoTableResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PutScoreIntoTableResult As Boolean)
            MyBase.New
            Me.PutScoreIntoTableResult = PutScoreIntoTableResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutScoreIntoTableWithPicRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutScoreIntoTableWithPic", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.PutScoreIntoTableWithPicRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.PutScoreIntoTableWithPicRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class PutScoreIntoTableWithPicRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Pass As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Score As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public table As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public picurl As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal table As String, ByVal picurl As String)
            MyBase.New
            Me.UserName = UserName
            Me.Pass = Pass
            Me.Score = Score
            Me.table = table
            Me.picurl = picurl
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutScoreIntoTableWithPicResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutScoreIntoTableWithPicResponse", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.PutScoreIntoTableWithPicResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.PutScoreIntoTableWithPicResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class PutScoreIntoTableWithPicResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public PutScoreIntoTableWithPicResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PutScoreIntoTableWithPicResult As Boolean)
            MyBase.New
            Me.PutScoreIntoTableWithPicResult = PutScoreIntoTableWithPicResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTopPlayersRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTopPlayers", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.GetTopPlayersRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.GetTopPlayersRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class GetTopPlayersRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public rules As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Players As System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore)
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal rules As String, ByVal Players As System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore))
            MyBase.New
            Me.rules = rules
            Me.Players = Players
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTopPlayersResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTopPlayersResponse", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.GetTopPlayersResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.GetTopPlayersResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class GetTopPlayersResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetTopPlayersResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Players As System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore)
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTopPlayersResult As Boolean, ByVal Players As System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore))
            MyBase.New
            Me.GetTopPlayersResult = GetTopPlayersResult
            Me.Players = Players
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetChempionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetChempion", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.GetChempionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.GetChempionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class GetChempionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public rules As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Name As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Score As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal rules As String, ByVal Name As String, ByVal Score As String)
            MyBase.New
            Me.rules = rules
            Me.Name = Name
            Me.Score = Score
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetChempionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetChempionResponse", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.GetChempionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.GetChempionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class GetChempionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public GetChempionResult As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Name As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Score As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetChempionResult As Boolean, ByVal Name As String, ByVal Score As String)
            MyBase.New
            Me.GetChempionResult = GetChempionResult
            Me.Name = Name
            Me.Score = Score
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface KniffelServiceSoapChannel
        Inherits KniffelPutScore.KniffelServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PutScoreCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PutScoreIntoTableCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PutScoreIntoTableWithPicCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetTopPlayersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Players() As System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore)
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore))
            End Get
        End Property
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GetChempionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Name() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        Public ReadOnly Property Score() As String
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(2),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class KniffelServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of KniffelPutScore.KniffelServiceSoap)
        Implements KniffelPutScore.KniffelServiceSoap
        
        Private onBeginPutScoreDelegate As BeginOperationDelegate
        
        Private onEndPutScoreDelegate As EndOperationDelegate
        
        Private onPutScoreCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginPutScoreIntoTableDelegate As BeginOperationDelegate
        
        Private onEndPutScoreIntoTableDelegate As EndOperationDelegate
        
        Private onPutScoreIntoTableCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginPutScoreIntoTableWithPicDelegate As BeginOperationDelegate
        
        Private onEndPutScoreIntoTableWithPicDelegate As EndOperationDelegate
        
        Private onPutScoreIntoTableWithPicCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginGetTopPlayersDelegate As BeginOperationDelegate
        
        Private onEndGetTopPlayersDelegate As EndOperationDelegate
        
        Private onGetTopPlayersCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginGetChempionDelegate As BeginOperationDelegate
        
        Private onEndGetChempionDelegate As EndOperationDelegate
        
        Private onGetChempionCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginOpenDelegate As BeginOperationDelegate
        
        Private onEndOpenDelegate As EndOperationDelegate
        
        Private onOpenCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginCloseDelegate As BeginOperationDelegate
        
        Private onEndCloseDelegate As EndOperationDelegate
        
        Private onCloseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Property CookieContainer() As System.Net.CookieContainer
            Get
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    Return httpCookieContainerManager.CookieContainer
                Else
                    Return Nothing
                End If
            End Get
            Set
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    httpCookieContainerManager.CookieContainer = value
                Else
                    Throw New System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC"& _ 
                            "ookieContainerBindingElement.")
                End If
            End Set
        End Property
        
        Public Event PutScoreCompleted As System.EventHandler(Of PutScoreCompletedEventArgs)
        
        Public Event PutScoreIntoTableCompleted As System.EventHandler(Of PutScoreIntoTableCompletedEventArgs)
        
        Public Event PutScoreIntoTableWithPicCompleted As System.EventHandler(Of PutScoreIntoTableWithPicCompletedEventArgs)
        
        Public Event GetTopPlayersCompleted As System.EventHandler(Of GetTopPlayersCompletedEventArgs)
        
        Public Event GetChempionCompleted As System.EventHandler(Of GetChempionCompletedEventArgs)
        
        Public Event OpenCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event CloseCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_BeginPutScore(ByVal request As KniffelPutScore.PutScoreRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginPutScore
            Return MyBase.Channel.BeginPutScore(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginPutScore(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As KniffelPutScore.PutScoreRequest = New KniffelPutScore.PutScoreRequest()
            inValue.Body = New KniffelPutScore.PutScoreRequestBody()
            inValue.Body.UserName = UserName
            inValue.Body.Pass = Pass
            inValue.Body.Score = Score
            Return CType(Me,KniffelPutScore.KniffelServiceSoap).BeginPutScore(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_EndPutScore(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreResponse Implements KniffelPutScore.KniffelServiceSoap.EndPutScore
            Return MyBase.Channel.EndPutScore(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndPutScore(ByVal result As System.IAsyncResult) As Boolean
            Dim retVal As KniffelPutScore.PutScoreResponse = CType(Me,KniffelPutScore.KniffelServiceSoap).EndPutScore(result)
            Return retVal.Body.PutScoreResult
        End Function
        
        Private Function OnBeginPutScore(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim UserName As String = CType(inValues(0),String)
            Dim Pass As String = CType(inValues(1),String)
            Dim Score As String = CType(inValues(2),String)
            Return Me.BeginPutScore(UserName, Pass, Score, callback, asyncState)
        End Function
        
        Private Function OnEndPutScore(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Boolean = Me.EndPutScore(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnPutScoreCompleted(ByVal state As Object)
            If (Not (Me.PutScoreCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent PutScoreCompleted(Me, New PutScoreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub PutScoreAsync(ByVal UserName As String, ByVal Pass As String, ByVal Score As String)
            Me.PutScoreAsync(UserName, Pass, Score, Nothing)
        End Sub
        
        Public Overloads Sub PutScoreAsync(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal userState As Object)
            If (Me.onBeginPutScoreDelegate Is Nothing) Then
                Me.onBeginPutScoreDelegate = AddressOf Me.OnBeginPutScore
            End If
            If (Me.onEndPutScoreDelegate Is Nothing) Then
                Me.onEndPutScoreDelegate = AddressOf Me.OnEndPutScore
            End If
            If (Me.onPutScoreCompletedDelegate Is Nothing) Then
                Me.onPutScoreCompletedDelegate = AddressOf Me.OnPutScoreCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginPutScoreDelegate, New Object() {UserName, Pass, Score}, Me.onEndPutScoreDelegate, Me.onPutScoreCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_BeginPutScoreIntoTable(ByVal request As KniffelPutScore.PutScoreIntoTableRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginPutScoreIntoTable
            Return MyBase.Channel.BeginPutScoreIntoTable(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginPutScoreIntoTable(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal table As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As KniffelPutScore.PutScoreIntoTableRequest = New KniffelPutScore.PutScoreIntoTableRequest()
            inValue.Body = New KniffelPutScore.PutScoreIntoTableRequestBody()
            inValue.Body.UserName = UserName
            inValue.Body.Pass = Pass
            inValue.Body.Score = Score
            inValue.Body.table = table
            Return CType(Me,KniffelPutScore.KniffelServiceSoap).BeginPutScoreIntoTable(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_EndPutScoreIntoTable(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreIntoTableResponse Implements KniffelPutScore.KniffelServiceSoap.EndPutScoreIntoTable
            Return MyBase.Channel.EndPutScoreIntoTable(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndPutScoreIntoTable(ByVal result As System.IAsyncResult) As Boolean
            Dim retVal As KniffelPutScore.PutScoreIntoTableResponse = CType(Me,KniffelPutScore.KniffelServiceSoap).EndPutScoreIntoTable(result)
            Return retVal.Body.PutScoreIntoTableResult
        End Function
        
        Private Function OnBeginPutScoreIntoTable(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim UserName As String = CType(inValues(0),String)
            Dim Pass As String = CType(inValues(1),String)
            Dim Score As String = CType(inValues(2),String)
            Dim table As String = CType(inValues(3),String)
            Return Me.BeginPutScoreIntoTable(UserName, Pass, Score, table, callback, asyncState)
        End Function
        
        Private Function OnEndPutScoreIntoTable(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Boolean = Me.EndPutScoreIntoTable(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnPutScoreIntoTableCompleted(ByVal state As Object)
            If (Not (Me.PutScoreIntoTableCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent PutScoreIntoTableCompleted(Me, New PutScoreIntoTableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub PutScoreIntoTableAsync(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal table As String)
            Me.PutScoreIntoTableAsync(UserName, Pass, Score, table, Nothing)
        End Sub
        
        Public Overloads Sub PutScoreIntoTableAsync(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal table As String, ByVal userState As Object)
            If (Me.onBeginPutScoreIntoTableDelegate Is Nothing) Then
                Me.onBeginPutScoreIntoTableDelegate = AddressOf Me.OnBeginPutScoreIntoTable
            End If
            If (Me.onEndPutScoreIntoTableDelegate Is Nothing) Then
                Me.onEndPutScoreIntoTableDelegate = AddressOf Me.OnEndPutScoreIntoTable
            End If
            If (Me.onPutScoreIntoTableCompletedDelegate Is Nothing) Then
                Me.onPutScoreIntoTableCompletedDelegate = AddressOf Me.OnPutScoreIntoTableCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginPutScoreIntoTableDelegate, New Object() {UserName, Pass, Score, table}, Me.onEndPutScoreIntoTableDelegate, Me.onPutScoreIntoTableCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_BeginPutScoreIntoTableWithPic(ByVal request As KniffelPutScore.PutScoreIntoTableWithPicRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginPutScoreIntoTableWithPic
            Return MyBase.Channel.BeginPutScoreIntoTableWithPic(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginPutScoreIntoTableWithPic(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal table As String, ByVal picurl As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As KniffelPutScore.PutScoreIntoTableWithPicRequest = New KniffelPutScore.PutScoreIntoTableWithPicRequest()
            inValue.Body = New KniffelPutScore.PutScoreIntoTableWithPicRequestBody()
            inValue.Body.UserName = UserName
            inValue.Body.Pass = Pass
            inValue.Body.Score = Score
            inValue.Body.table = table
            inValue.Body.picurl = picurl
            Return CType(Me,KniffelPutScore.KniffelServiceSoap).BeginPutScoreIntoTableWithPic(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_EndPutScoreIntoTableWithPic(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreIntoTableWithPicResponse Implements KniffelPutScore.KniffelServiceSoap.EndPutScoreIntoTableWithPic
            Return MyBase.Channel.EndPutScoreIntoTableWithPic(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndPutScoreIntoTableWithPic(ByVal result As System.IAsyncResult) As Boolean
            Dim retVal As KniffelPutScore.PutScoreIntoTableWithPicResponse = CType(Me,KniffelPutScore.KniffelServiceSoap).EndPutScoreIntoTableWithPic(result)
            Return retVal.Body.PutScoreIntoTableWithPicResult
        End Function
        
        Private Function OnBeginPutScoreIntoTableWithPic(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim UserName As String = CType(inValues(0),String)
            Dim Pass As String = CType(inValues(1),String)
            Dim Score As String = CType(inValues(2),String)
            Dim table As String = CType(inValues(3),String)
            Dim picurl As String = CType(inValues(4),String)
            Return Me.BeginPutScoreIntoTableWithPic(UserName, Pass, Score, table, picurl, callback, asyncState)
        End Function
        
        Private Function OnEndPutScoreIntoTableWithPic(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Boolean = Me.EndPutScoreIntoTableWithPic(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnPutScoreIntoTableWithPicCompleted(ByVal state As Object)
            If (Not (Me.PutScoreIntoTableWithPicCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent PutScoreIntoTableWithPicCompleted(Me, New PutScoreIntoTableWithPicCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub PutScoreIntoTableWithPicAsync(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal table As String, ByVal picurl As String)
            Me.PutScoreIntoTableWithPicAsync(UserName, Pass, Score, table, picurl, Nothing)
        End Sub
        
        Public Overloads Sub PutScoreIntoTableWithPicAsync(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal table As String, ByVal picurl As String, ByVal userState As Object)
            If (Me.onBeginPutScoreIntoTableWithPicDelegate Is Nothing) Then
                Me.onBeginPutScoreIntoTableWithPicDelegate = AddressOf Me.OnBeginPutScoreIntoTableWithPic
            End If
            If (Me.onEndPutScoreIntoTableWithPicDelegate Is Nothing) Then
                Me.onEndPutScoreIntoTableWithPicDelegate = AddressOf Me.OnEndPutScoreIntoTableWithPic
            End If
            If (Me.onPutScoreIntoTableWithPicCompletedDelegate Is Nothing) Then
                Me.onPutScoreIntoTableWithPicCompletedDelegate = AddressOf Me.OnPutScoreIntoTableWithPicCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginPutScoreIntoTableWithPicDelegate, New Object() {UserName, Pass, Score, table, picurl}, Me.onEndPutScoreIntoTableWithPicDelegate, Me.onPutScoreIntoTableWithPicCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_BeginGetTopPlayers(ByVal request As KniffelPutScore.GetTopPlayersRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginGetTopPlayers
            Return MyBase.Channel.BeginGetTopPlayers(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginGetTopPlayers(ByVal rules As String, ByVal Players As System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore), ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As KniffelPutScore.GetTopPlayersRequest = New KniffelPutScore.GetTopPlayersRequest()
            inValue.Body = New KniffelPutScore.GetTopPlayersRequestBody()
            inValue.Body.rules = rules
            inValue.Body.Players = Players
            Return CType(Me,KniffelPutScore.KniffelServiceSoap).BeginGetTopPlayers(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_EndGetTopPlayers(ByVal result As System.IAsyncResult) As KniffelPutScore.GetTopPlayersResponse Implements KniffelPutScore.KniffelServiceSoap.EndGetTopPlayers
            Return MyBase.Channel.EndGetTopPlayers(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndGetTopPlayers(ByVal result As System.IAsyncResult, <System.Runtime.InteropServices.OutAttribute()> ByRef Players As System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore)) As Boolean
            Dim retVal As KniffelPutScore.GetTopPlayersResponse = CType(Me,KniffelPutScore.KniffelServiceSoap).EndGetTopPlayers(result)
            Players = retVal.Body.Players
            Return retVal.Body.GetTopPlayersResult
        End Function
        
        Private Function OnBeginGetTopPlayers(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim rules As String = CType(inValues(0),String)
            Dim Players As System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore) = CType(inValues(1),System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore))
            Return Me.BeginGetTopPlayers(rules, Players, callback, asyncState)
        End Function
        
        Private Function OnEndGetTopPlayers(ByVal result As System.IAsyncResult) As Object()
            Dim Players As System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore) = Me.GetDefaultValueForInitialization(Of System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore))
            Dim retVal As Boolean = Me.EndGetTopPlayers(result, Players)
            Return New Object() {Players, retVal}
        End Function
        
        Private Sub OnGetTopPlayersCompleted(ByVal state As Object)
            If (Not (Me.GetTopPlayersCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetTopPlayersCompleted(Me, New GetTopPlayersCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetTopPlayersAsync(ByVal rules As String, ByVal Players As System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore))
            Me.GetTopPlayersAsync(rules, Players, Nothing)
        End Sub
        
        Public Overloads Sub GetTopPlayersAsync(ByVal rules As String, ByVal Players As System.Collections.ObjectModel.ObservableCollection(Of KniffelPutScore.KniffelScore), ByVal userState As Object)
            If (Me.onBeginGetTopPlayersDelegate Is Nothing) Then
                Me.onBeginGetTopPlayersDelegate = AddressOf Me.OnBeginGetTopPlayers
            End If
            If (Me.onEndGetTopPlayersDelegate Is Nothing) Then
                Me.onEndGetTopPlayersDelegate = AddressOf Me.OnEndGetTopPlayers
            End If
            If (Me.onGetTopPlayersCompletedDelegate Is Nothing) Then
                Me.onGetTopPlayersCompletedDelegate = AddressOf Me.OnGetTopPlayersCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetTopPlayersDelegate, New Object() {rules, Players}, Me.onEndGetTopPlayersDelegate, Me.onGetTopPlayersCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_BeginGetChempion(ByVal request As KniffelPutScore.GetChempionRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginGetChempion
            Return MyBase.Channel.BeginGetChempion(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginGetChempion(ByVal rules As String, ByVal Name As String, ByVal Score As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As KniffelPutScore.GetChempionRequest = New KniffelPutScore.GetChempionRequest()
            inValue.Body = New KniffelPutScore.GetChempionRequestBody()
            inValue.Body.rules = rules
            inValue.Body.Name = Name
            inValue.Body.Score = Score
            Return CType(Me,KniffelPutScore.KniffelServiceSoap).BeginGetChempion(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_EndGetChempion(ByVal result As System.IAsyncResult) As KniffelPutScore.GetChempionResponse Implements KniffelPutScore.KniffelServiceSoap.EndGetChempion
            Return MyBase.Channel.EndGetChempion(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndGetChempion(ByVal result As System.IAsyncResult, <System.Runtime.InteropServices.OutAttribute()> ByRef Name As String, <System.Runtime.InteropServices.OutAttribute()> ByRef Score As String) As Boolean
            Dim retVal As KniffelPutScore.GetChempionResponse = CType(Me,KniffelPutScore.KniffelServiceSoap).EndGetChempion(result)
            Name = retVal.Body.Name
            Score = retVal.Body.Score
            Return retVal.Body.GetChempionResult
        End Function
        
        Private Function OnBeginGetChempion(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim rules As String = CType(inValues(0),String)
            Dim Name As String = CType(inValues(1),String)
            Dim Score As String = CType(inValues(2),String)
            Return Me.BeginGetChempion(rules, Name, Score, callback, asyncState)
        End Function
        
        Private Function OnEndGetChempion(ByVal result As System.IAsyncResult) As Object()
            Dim Name As String = Me.GetDefaultValueForInitialization(Of String)
            Dim Score As String = Me.GetDefaultValueForInitialization(Of String)
            Dim retVal As Boolean = Me.EndGetChempion(result, Name, Score)
            Return New Object() {Name, Score, retVal}
        End Function
        
        Private Sub OnGetChempionCompleted(ByVal state As Object)
            If (Not (Me.GetChempionCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent GetChempionCompleted(Me, New GetChempionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub GetChempionAsync(ByVal rules As String, ByVal Name As String, ByVal Score As String)
            Me.GetChempionAsync(rules, Name, Score, Nothing)
        End Sub
        
        Public Overloads Sub GetChempionAsync(ByVal rules As String, ByVal Name As String, ByVal Score As String, ByVal userState As Object)
            If (Me.onBeginGetChempionDelegate Is Nothing) Then
                Me.onBeginGetChempionDelegate = AddressOf Me.OnBeginGetChempion
            End If
            If (Me.onEndGetChempionDelegate Is Nothing) Then
                Me.onEndGetChempionDelegate = AddressOf Me.OnEndGetChempion
            End If
            If (Me.onGetChempionCompletedDelegate Is Nothing) Then
                Me.onGetChempionCompletedDelegate = AddressOf Me.OnGetChempionCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginGetChempionDelegate, New Object() {rules, Name, Score}, Me.onEndGetChempionDelegate, Me.onGetChempionCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginOpen(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(callback, asyncState)
        End Function
        
        Private Function OnEndOpen(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndOpen(result)
            Return Nothing
        End Function
        
        Private Sub OnOpenCompleted(ByVal state As Object)
            If (Not (Me.OpenCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent OpenCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub OpenAsync()
            Me.OpenAsync(Nothing)
        End Sub
        
        Public Overloads Sub OpenAsync(ByVal userState As Object)
            If (Me.onBeginOpenDelegate Is Nothing) Then
                Me.onBeginOpenDelegate = AddressOf Me.OnBeginOpen
            End If
            If (Me.onEndOpenDelegate Is Nothing) Then
                Me.onEndOpenDelegate = AddressOf Me.OnEndOpen
            End If
            If (Me.onOpenCompletedDelegate Is Nothing) Then
                Me.onOpenCompletedDelegate = AddressOf Me.OnOpenCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginOpenDelegate, Nothing, Me.onEndOpenDelegate, Me.onOpenCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginClose(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(callback, asyncState)
        End Function
        
        Private Function OnEndClose(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndClose(result)
            Return Nothing
        End Function
        
        Private Sub OnCloseCompleted(ByVal state As Object)
            If (Not (Me.CloseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CloseCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CloseAsync()
            Me.CloseAsync(Nothing)
        End Sub
        
        Public Overloads Sub CloseAsync(ByVal userState As Object)
            If (Me.onBeginCloseDelegate Is Nothing) Then
                Me.onBeginCloseDelegate = AddressOf Me.OnBeginClose
            End If
            If (Me.onEndCloseDelegate Is Nothing) Then
                Me.onEndCloseDelegate = AddressOf Me.OnEndClose
            End If
            If (Me.onCloseCompletedDelegate Is Nothing) Then
                Me.onCloseCompletedDelegate = AddressOf Me.OnCloseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCloseDelegate, Nothing, Me.onEndCloseDelegate, Me.onCloseCompletedDelegate, userState)
        End Sub
        
        Protected Overrides Function CreateChannel() As KniffelPutScore.KniffelServiceSoap
            Return New KniffelServiceSoapClientChannel(Me)
        End Function
        
        Private Class KniffelServiceSoapClientChannel
            Inherits ChannelBase(Of KniffelPutScore.KniffelServiceSoap)
            Implements KniffelPutScore.KniffelServiceSoap
            
            Public Sub New(ByVal client As System.ServiceModel.ClientBase(Of KniffelPutScore.KniffelServiceSoap))
                MyBase.New(client)
            End Sub
            
            Public Function BeginPutScore(ByVal request As KniffelPutScore.PutScoreRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginPutScore
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("PutScore", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndPutScore(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreResponse Implements KniffelPutScore.KniffelServiceSoap.EndPutScore
                Dim _args((0) - 1) As Object
                Dim _result As KniffelPutScore.PutScoreResponse = CType(MyBase.EndInvoke("PutScore", _args, result),KniffelPutScore.PutScoreResponse)
                Return _result
            End Function
            
            Public Function BeginPutScoreIntoTable(ByVal request As KniffelPutScore.PutScoreIntoTableRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginPutScoreIntoTable
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("PutScoreIntoTable", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndPutScoreIntoTable(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreIntoTableResponse Implements KniffelPutScore.KniffelServiceSoap.EndPutScoreIntoTable
                Dim _args((0) - 1) As Object
                Dim _result As KniffelPutScore.PutScoreIntoTableResponse = CType(MyBase.EndInvoke("PutScoreIntoTable", _args, result),KniffelPutScore.PutScoreIntoTableResponse)
                Return _result
            End Function
            
            Public Function BeginPutScoreIntoTableWithPic(ByVal request As KniffelPutScore.PutScoreIntoTableWithPicRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginPutScoreIntoTableWithPic
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("PutScoreIntoTableWithPic", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndPutScoreIntoTableWithPic(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreIntoTableWithPicResponse Implements KniffelPutScore.KniffelServiceSoap.EndPutScoreIntoTableWithPic
                Dim _args((0) - 1) As Object
                Dim _result As KniffelPutScore.PutScoreIntoTableWithPicResponse = CType(MyBase.EndInvoke("PutScoreIntoTableWithPic", _args, result),KniffelPutScore.PutScoreIntoTableWithPicResponse)
                Return _result
            End Function
            
            Public Function BeginGetTopPlayers(ByVal request As KniffelPutScore.GetTopPlayersRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginGetTopPlayers
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("GetTopPlayers", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndGetTopPlayers(ByVal result As System.IAsyncResult) As KniffelPutScore.GetTopPlayersResponse Implements KniffelPutScore.KniffelServiceSoap.EndGetTopPlayers
                Dim _args((0) - 1) As Object
                Dim _result As KniffelPutScore.GetTopPlayersResponse = CType(MyBase.EndInvoke("GetTopPlayers", _args, result),KniffelPutScore.GetTopPlayersResponse)
                Return _result
            End Function
            
            Public Function BeginGetChempion(ByVal request As KniffelPutScore.GetChempionRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginGetChempion
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("GetChempion", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndGetChempion(ByVal result As System.IAsyncResult) As KniffelPutScore.GetChempionResponse Implements KniffelPutScore.KniffelServiceSoap.EndGetChempion
                Dim _args((0) - 1) As Object
                Dim _result As KniffelPutScore.GetChempionResponse = CType(MyBase.EndInvoke("GetChempion", _args, result),KniffelPutScore.GetChempionResponse)
                Return _result
            End Function
        End Class
    End Class
End Namespace
