//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 11.0.50727.1
// 
namespace DicePokerRT.KniffelLeaderBoardService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KniffelScore", Namespace="http://www.sanet.com/")]
    public partial class KniffelScore : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int HighScoreField;
        
        private int IdField;
        
        private int TotalField;
        
        private int GamesField;
        
        private string PlayerField;
        
        private string PassField;
        
        private string PicUrlField;
        
        private string TableField;
        
        private int PlaceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int HighScore {
            get {
                return this.HighScoreField;
            }
            set {
                if ((this.HighScoreField.Equals(value) != true)) {
                    this.HighScoreField = value;
                    this.RaisePropertyChanged("HighScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Games {
            get {
                return this.GamesField;
            }
            set {
                if ((this.GamesField.Equals(value) != true)) {
                    this.GamesField = value;
                    this.RaisePropertyChanged("Games");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Player {
            get {
                return this.PlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerField, value) != true)) {
                    this.PlayerField = value;
                    this.RaisePropertyChanged("Player");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PicUrl {
            get {
                return this.PicUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PicUrlField, value) != true)) {
                    this.PicUrlField = value;
                    this.RaisePropertyChanged("PicUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Table {
            get {
                return this.TableField;
            }
            set {
                if ((object.ReferenceEquals(this.TableField, value) != true)) {
                    this.TableField = value;
                    this.RaisePropertyChanged("Table");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((this.PlaceField.Equals(value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sanet.com/", ConfigurationName="KniffelLeaderBoardService.KniffelServiceSoap")]
    public interface KniffelServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/PutScore", ReplyAction="*")]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.PutScoreResponse> PutScoreAsync(DicePokerRT.KniffelLeaderBoardService.PutScoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/PutScoreIntoTable", ReplyAction="*")]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableResponse> PutScoreIntoTableAsync(DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/PutScoreIntoTableWithPic", ReplyAction="*")]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableWithPicResponse> PutScoreIntoTableWithPicAsync(DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableWithPicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetTopPlayers", ReplyAction="*")]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.GetTopPlayersResponse> GetTopPlayersAsync(DicePokerRT.KniffelLeaderBoardService.GetTopPlayersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetChempion", ReplyAction="*")]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.GetChempionResponse> GetChempionAsync(DicePokerRT.KniffelLeaderBoardService.GetChempionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetLastWeekChempion", ReplyAction="*")]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.GetLastWeekChempionResponse> GetLastWeekChempionAsync(DicePokerRT.KniffelLeaderBoardService.GetLastWeekChempionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetLastDayChempion", ReplyAction="*")]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.GetLastDayChempionResponse> GetLastDayChempionAsync(DicePokerRT.KniffelLeaderBoardService.GetLastDayChempionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScore", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.PutScoreRequestBody Body;
        
        public PutScoreRequest() {
        }
        
        public PutScoreRequest(DicePokerRT.KniffelLeaderBoardService.PutScoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public PutScoreRequestBody() {
        }
        
        public PutScoreRequestBody(string UserName, string Pass, string Score) {
            this.UserName = UserName;
            this.Pass = Pass;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreResponse", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.PutScoreResponseBody Body;
        
        public PutScoreResponse() {
        }
        
        public PutScoreResponse(DicePokerRT.KniffelLeaderBoardService.PutScoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PutScoreResult;
        
        public PutScoreResponseBody() {
        }
        
        public PutScoreResponseBody(bool PutScoreResult) {
            this.PutScoreResult = PutScoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTable", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableRequestBody Body;
        
        public PutScoreIntoTableRequest() {
        }
        
        public PutScoreIntoTableRequest(DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string table;
        
        public PutScoreIntoTableRequestBody() {
        }
        
        public PutScoreIntoTableRequestBody(string UserName, string Pass, string Score, string table) {
            this.UserName = UserName;
            this.Pass = Pass;
            this.Score = Score;
            this.table = table;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTableResponse", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableResponseBody Body;
        
        public PutScoreIntoTableResponse() {
        }
        
        public PutScoreIntoTableResponse(DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PutScoreIntoTableResult;
        
        public PutScoreIntoTableResponseBody() {
        }
        
        public PutScoreIntoTableResponseBody(bool PutScoreIntoTableResult) {
            this.PutScoreIntoTableResult = PutScoreIntoTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableWithPicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTableWithPic", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableWithPicRequestBody Body;
        
        public PutScoreIntoTableWithPicRequest() {
        }
        
        public PutScoreIntoTableWithPicRequest(DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableWithPicRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableWithPicRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string table;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string picurl;
        
        public PutScoreIntoTableWithPicRequestBody() {
        }
        
        public PutScoreIntoTableWithPicRequestBody(string UserName, string Pass, string Score, string table, string picurl) {
            this.UserName = UserName;
            this.Pass = Pass;
            this.Score = Score;
            this.table = table;
            this.picurl = picurl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableWithPicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTableWithPicResponse", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableWithPicResponseBody Body;
        
        public PutScoreIntoTableWithPicResponse() {
        }
        
        public PutScoreIntoTableWithPicResponse(DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableWithPicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableWithPicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PutScoreIntoTableWithPicResult;
        
        public PutScoreIntoTableWithPicResponseBody() {
        }
        
        public PutScoreIntoTableWithPicResponseBody(bool PutScoreIntoTableWithPicResult) {
            this.PutScoreIntoTableWithPicResult = PutScoreIntoTableWithPicResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopPlayersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopPlayers", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.GetTopPlayersRequestBody Body;
        
        public GetTopPlayersRequest() {
        }
        
        public GetTopPlayersRequest(DicePokerRT.KniffelLeaderBoardService.GetTopPlayersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetTopPlayersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rules;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.ObjectModel.ObservableCollection<DicePokerRT.KniffelLeaderBoardService.KniffelScore> Players;
        
        public GetTopPlayersRequestBody() {
        }
        
        public GetTopPlayersRequestBody(string rules, System.Collections.ObjectModel.ObservableCollection<DicePokerRT.KniffelLeaderBoardService.KniffelScore> Players) {
            this.rules = rules;
            this.Players = Players;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopPlayersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopPlayersResponse", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.GetTopPlayersResponseBody Body;
        
        public GetTopPlayersResponse() {
        }
        
        public GetTopPlayersResponse(DicePokerRT.KniffelLeaderBoardService.GetTopPlayersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetTopPlayersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetTopPlayersResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.ObjectModel.ObservableCollection<DicePokerRT.KniffelLeaderBoardService.KniffelScore> Players;
        
        public GetTopPlayersResponseBody() {
        }
        
        public GetTopPlayersResponseBody(bool GetTopPlayersResult, System.Collections.ObjectModel.ObservableCollection<DicePokerRT.KniffelLeaderBoardService.KniffelScore> Players) {
            this.GetTopPlayersResult = GetTopPlayersResult;
            this.Players = Players;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChempionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChempion", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.GetChempionRequestBody Body;
        
        public GetChempionRequest() {
        }
        
        public GetChempionRequest(DicePokerRT.KniffelLeaderBoardService.GetChempionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetChempionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rules;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetChempionRequestBody() {
        }
        
        public GetChempionRequestBody(string rules, string Name, string Score) {
            this.rules = rules;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChempionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChempionResponse", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.GetChempionResponseBody Body;
        
        public GetChempionResponse() {
        }
        
        public GetChempionResponse(DicePokerRT.KniffelLeaderBoardService.GetChempionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetChempionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetChempionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetChempionResponseBody() {
        }
        
        public GetChempionResponseBody(bool GetChempionResult, string Name, string Score) {
            this.GetChempionResult = GetChempionResult;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastWeekChempionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastWeekChempion", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.GetLastWeekChempionRequestBody Body;
        
        public GetLastWeekChempionRequest() {
        }
        
        public GetLastWeekChempionRequest(DicePokerRT.KniffelLeaderBoardService.GetLastWeekChempionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetLastWeekChempionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rules;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetLastWeekChempionRequestBody() {
        }
        
        public GetLastWeekChempionRequestBody(string rules, string Name, string Score) {
            this.rules = rules;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastWeekChempionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastWeekChempionResponse", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.GetLastWeekChempionResponseBody Body;
        
        public GetLastWeekChempionResponse() {
        }
        
        public GetLastWeekChempionResponse(DicePokerRT.KniffelLeaderBoardService.GetLastWeekChempionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetLastWeekChempionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetLastWeekChempionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetLastWeekChempionResponseBody() {
        }
        
        public GetLastWeekChempionResponseBody(bool GetLastWeekChempionResult, string Name, string Score) {
            this.GetLastWeekChempionResult = GetLastWeekChempionResult;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastDayChempionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastDayChempion", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.GetLastDayChempionRequestBody Body;
        
        public GetLastDayChempionRequest() {
        }
        
        public GetLastDayChempionRequest(DicePokerRT.KniffelLeaderBoardService.GetLastDayChempionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetLastDayChempionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rules;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetLastDayChempionRequestBody() {
        }
        
        public GetLastDayChempionRequestBody(string rules, string Name, string Score) {
            this.rules = rules;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastDayChempionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastDayChempionResponse", Namespace="http://www.sanet.com/", Order=0)]
        public DicePokerRT.KniffelLeaderBoardService.GetLastDayChempionResponseBody Body;
        
        public GetLastDayChempionResponse() {
        }
        
        public GetLastDayChempionResponse(DicePokerRT.KniffelLeaderBoardService.GetLastDayChempionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetLastDayChempionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetLastDayChempionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetLastDayChempionResponseBody() {
        }
        
        public GetLastDayChempionResponseBody(bool GetLastDayChempionResult, string Name, string Score) {
            this.GetLastDayChempionResult = GetLastDayChempionResult;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KniffelServiceSoapChannel : DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KniffelServiceSoapClient : System.ServiceModel.ClientBase<DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap>, DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KniffelServiceSoapClient() : 
                base(KniffelServiceSoapClient.GetDefaultBinding(), KniffelServiceSoapClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.KniffelServiceSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KniffelServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(KniffelServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), KniffelServiceSoapClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KniffelServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KniffelServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KniffelServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KniffelServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KniffelServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.PutScoreResponse> DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap.PutScoreAsync(DicePokerRT.KniffelLeaderBoardService.PutScoreRequest request) {
            return base.Channel.PutScoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.PutScoreResponse> PutScoreAsync(string UserName, string Pass, string Score) {
            DicePokerRT.KniffelLeaderBoardService.PutScoreRequest inValue = new DicePokerRT.KniffelLeaderBoardService.PutScoreRequest();
            inValue.Body = new DicePokerRT.KniffelLeaderBoardService.PutScoreRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pass = Pass;
            inValue.Body.Score = Score;
            return ((DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap)(this)).PutScoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableResponse> DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap.PutScoreIntoTableAsync(DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableRequest request) {
            return base.Channel.PutScoreIntoTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableResponse> PutScoreIntoTableAsync(string UserName, string Pass, string Score, string table) {
            DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableRequest inValue = new DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableRequest();
            inValue.Body = new DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pass = Pass;
            inValue.Body.Score = Score;
            inValue.Body.table = table;
            return ((DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap)(this)).PutScoreIntoTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableWithPicResponse> DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap.PutScoreIntoTableWithPicAsync(DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableWithPicRequest request) {
            return base.Channel.PutScoreIntoTableWithPicAsync(request);
        }
        
        public System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableWithPicResponse> PutScoreIntoTableWithPicAsync(string UserName, string Pass, string Score, string table, string picurl) {
            DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableWithPicRequest inValue = new DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableWithPicRequest();
            inValue.Body = new DicePokerRT.KniffelLeaderBoardService.PutScoreIntoTableWithPicRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pass = Pass;
            inValue.Body.Score = Score;
            inValue.Body.table = table;
            inValue.Body.picurl = picurl;
            return ((DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap)(this)).PutScoreIntoTableWithPicAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.GetTopPlayersResponse> DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap.GetTopPlayersAsync(DicePokerRT.KniffelLeaderBoardService.GetTopPlayersRequest request) {
            return base.Channel.GetTopPlayersAsync(request);
        }
        
        public System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.GetTopPlayersResponse> GetTopPlayersAsync(string rules, System.Collections.ObjectModel.ObservableCollection<DicePokerRT.KniffelLeaderBoardService.KniffelScore> Players) {
            DicePokerRT.KniffelLeaderBoardService.GetTopPlayersRequest inValue = new DicePokerRT.KniffelLeaderBoardService.GetTopPlayersRequest();
            inValue.Body = new DicePokerRT.KniffelLeaderBoardService.GetTopPlayersRequestBody();
            inValue.Body.rules = rules;
            inValue.Body.Players = Players;
            return ((DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap)(this)).GetTopPlayersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.GetChempionResponse> DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap.GetChempionAsync(DicePokerRT.KniffelLeaderBoardService.GetChempionRequest request) {
            return base.Channel.GetChempionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.GetChempionResponse> GetChempionAsync(string rules, string Name, string Score) {
            DicePokerRT.KniffelLeaderBoardService.GetChempionRequest inValue = new DicePokerRT.KniffelLeaderBoardService.GetChempionRequest();
            inValue.Body = new DicePokerRT.KniffelLeaderBoardService.GetChempionRequestBody();
            inValue.Body.rules = rules;
            inValue.Body.Name = Name;
            inValue.Body.Score = Score;
            return ((DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap)(this)).GetChempionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.GetLastWeekChempionResponse> DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap.GetLastWeekChempionAsync(DicePokerRT.KniffelLeaderBoardService.GetLastWeekChempionRequest request) {
            return base.Channel.GetLastWeekChempionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.GetLastWeekChempionResponse> GetLastWeekChempionAsync(string rules, string Name, string Score) {
            DicePokerRT.KniffelLeaderBoardService.GetLastWeekChempionRequest inValue = new DicePokerRT.KniffelLeaderBoardService.GetLastWeekChempionRequest();
            inValue.Body = new DicePokerRT.KniffelLeaderBoardService.GetLastWeekChempionRequestBody();
            inValue.Body.rules = rules;
            inValue.Body.Name = Name;
            inValue.Body.Score = Score;
            return ((DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap)(this)).GetLastWeekChempionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.GetLastDayChempionResponse> DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap.GetLastDayChempionAsync(DicePokerRT.KniffelLeaderBoardService.GetLastDayChempionRequest request) {
            return base.Channel.GetLastDayChempionAsync(request);
        }
        
        public System.Threading.Tasks.Task<DicePokerRT.KniffelLeaderBoardService.GetLastDayChempionResponse> GetLastDayChempionAsync(string rules, string Name, string Score) {
            DicePokerRT.KniffelLeaderBoardService.GetLastDayChempionRequest inValue = new DicePokerRT.KniffelLeaderBoardService.GetLastDayChempionRequest();
            inValue.Body = new DicePokerRT.KniffelLeaderBoardService.GetLastDayChempionRequestBody();
            inValue.Body.rules = rules;
            inValue.Body.Name = Name;
            inValue.Body.Score = Score;
            return ((DicePokerRT.KniffelLeaderBoardService.KniffelServiceSoap)(this)).GetLastDayChempionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.KniffelServiceSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.KniffelServiceSoap)) {
                return new System.ServiceModel.EndpointAddress("http://sanet.by/KniffelService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return KniffelServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.KniffelServiceSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return KniffelServiceSoapClient.GetEndpointAddress(EndpointConfiguration.KniffelServiceSoap);
        }
        
        public enum EndpointConfiguration {
            
            KniffelServiceSoap,
        }
    }
}
