//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudServer.KniffelService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KniffelScore", Namespace="http://www.sanet.com/")]
    [System.SerializableAttribute()]
    public partial class KniffelScore : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int HighScoreField;
        
        private int IdField;
        
        private int TotalField;
        
        private int GamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PicUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableField;
        
        private int PlaceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int HighScore {
            get {
                return this.HighScoreField;
            }
            set {
                if ((this.HighScoreField.Equals(value) != true)) {
                    this.HighScoreField = value;
                    this.RaisePropertyChanged("HighScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Games {
            get {
                return this.GamesField;
            }
            set {
                if ((this.GamesField.Equals(value) != true)) {
                    this.GamesField = value;
                    this.RaisePropertyChanged("Games");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Player {
            get {
                return this.PlayerField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerField, value) != true)) {
                    this.PlayerField = value;
                    this.RaisePropertyChanged("Player");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PicUrl {
            get {
                return this.PicUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PicUrlField, value) != true)) {
                    this.PicUrlField = value;
                    this.RaisePropertyChanged("PicUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Table {
            get {
                return this.TableField;
            }
            set {
                if ((object.ReferenceEquals(this.TableField, value) != true)) {
                    this.TableField = value;
                    this.RaisePropertyChanged("Table");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Place {
            get {
                return this.PlaceField;
            }
            set {
                if ((this.PlaceField.Equals(value) != true)) {
                    this.PlaceField = value;
                    this.RaisePropertyChanged("Place");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.sanet.com/", ConfigurationName="KniffelService.KniffelServiceSoap")]
    public interface KniffelServiceSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.sanet.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/PutScore", ReplyAction="*")]
        CloudServer.KniffelService.PutScoreResponse PutScore(CloudServer.KniffelService.PutScoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/PutScore", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudServer.KniffelService.PutScoreResponse> PutScoreAsync(CloudServer.KniffelService.PutScoreRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.sanet.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/PutScoreIntoTable", ReplyAction="*")]
        CloudServer.KniffelService.PutScoreIntoTableResponse PutScoreIntoTable(CloudServer.KniffelService.PutScoreIntoTableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/PutScoreIntoTable", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudServer.KniffelService.PutScoreIntoTableResponse> PutScoreIntoTableAsync(CloudServer.KniffelService.PutScoreIntoTableRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.sanet.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/PutScoreIntoTableWithPic", ReplyAction="*")]
        CloudServer.KniffelService.PutScoreIntoTableWithPicResponse PutScoreIntoTableWithPic(CloudServer.KniffelService.PutScoreIntoTableWithPicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/PutScoreIntoTableWithPic", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudServer.KniffelService.PutScoreIntoTableWithPicResponse> PutScoreIntoTableWithPicAsync(CloudServer.KniffelService.PutScoreIntoTableWithPicRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.sanet.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/PutScoreIntoTableWithPicPureName", ReplyAction="*")]
        CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameResponse PutScoreIntoTableWithPicPureName(CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/PutScoreIntoTableWithPicPureName", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameResponse> PutScoreIntoTableWithPicPureNameAsync(CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameRequest request);
        
        // CODEGEN: Generating message contract since element name source from namespace http://www.sanet.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/PutOnlineServerLog", ReplyAction="*")]
        CloudServer.KniffelService.PutOnlineServerLogResponse PutOnlineServerLog(CloudServer.KniffelService.PutOnlineServerLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/PutOnlineServerLog", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudServer.KniffelService.PutOnlineServerLogResponse> PutOnlineServerLogAsync(CloudServer.KniffelService.PutOnlineServerLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetTopPlayers", ReplyAction="*")]
        CloudServer.KniffelService.GetTopPlayersResponse GetTopPlayers(CloudServer.KniffelService.GetTopPlayersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetTopPlayers", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudServer.KniffelService.GetTopPlayersResponse> GetTopPlayersAsync(CloudServer.KniffelService.GetTopPlayersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetChempion", ReplyAction="*")]
        CloudServer.KniffelService.GetChempionResponse GetChempion(CloudServer.KniffelService.GetChempionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetChempion", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudServer.KniffelService.GetChempionResponse> GetChempionAsync(CloudServer.KniffelService.GetChempionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetLastWeekChempion", ReplyAction="*")]
        CloudServer.KniffelService.GetLastWeekChempionResponse GetLastWeekChempion(CloudServer.KniffelService.GetLastWeekChempionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetLastWeekChempion", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudServer.KniffelService.GetLastWeekChempionResponse> GetLastWeekChempionAsync(CloudServer.KniffelService.GetLastWeekChempionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetLastDayChempion", ReplyAction="*")]
        CloudServer.KniffelService.GetLastDayChempionResponse GetLastDayChempion(CloudServer.KniffelService.GetLastDayChempionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetLastDayChempion", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudServer.KniffelService.GetLastDayChempionResponse> GetLastDayChempionAsync(CloudServer.KniffelService.GetLastDayChempionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetPlayersMagics", ReplyAction="*")]
        CloudServer.KniffelService.GetPlayersMagicsResponse GetPlayersMagics(CloudServer.KniffelService.GetPlayersMagicsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/GetPlayersMagics", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudServer.KniffelService.GetPlayersMagicsResponse> GetPlayersMagicsAsync(CloudServer.KniffelService.GetPlayersMagicsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://www.sanet.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/AddPlayersMagics", ReplyAction="*")]
        CloudServer.KniffelService.AddPlayersMagicsResponse AddPlayersMagics(CloudServer.KniffelService.AddPlayersMagicsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.sanet.com/AddPlayersMagics", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudServer.KniffelService.AddPlayersMagicsResponse> AddPlayersMagicsAsync(CloudServer.KniffelService.AddPlayersMagicsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScore", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.PutScoreRequestBody Body;
        
        public PutScoreRequest() {
        }
        
        public PutScoreRequest(CloudServer.KniffelService.PutScoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public PutScoreRequestBody() {
        }
        
        public PutScoreRequestBody(string UserName, string Pass, string Score) {
            this.UserName = UserName;
            this.Pass = Pass;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreResponse", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.PutScoreResponseBody Body;
        
        public PutScoreResponse() {
        }
        
        public PutScoreResponse(CloudServer.KniffelService.PutScoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PutScoreResult;
        
        public PutScoreResponseBody() {
        }
        
        public PutScoreResponseBody(bool PutScoreResult) {
            this.PutScoreResult = PutScoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTable", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.PutScoreIntoTableRequestBody Body;
        
        public PutScoreIntoTableRequest() {
        }
        
        public PutScoreIntoTableRequest(CloudServer.KniffelService.PutScoreIntoTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string table;
        
        public PutScoreIntoTableRequestBody() {
        }
        
        public PutScoreIntoTableRequestBody(string UserName, string Pass, string Score, string table) {
            this.UserName = UserName;
            this.Pass = Pass;
            this.Score = Score;
            this.table = table;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTableResponse", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.PutScoreIntoTableResponseBody Body;
        
        public PutScoreIntoTableResponse() {
        }
        
        public PutScoreIntoTableResponse(CloudServer.KniffelService.PutScoreIntoTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PutScoreIntoTableResult;
        
        public PutScoreIntoTableResponseBody() {
        }
        
        public PutScoreIntoTableResponseBody(bool PutScoreIntoTableResult) {
            this.PutScoreIntoTableResult = PutScoreIntoTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableWithPicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTableWithPic", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.PutScoreIntoTableWithPicRequestBody Body;
        
        public PutScoreIntoTableWithPicRequest() {
        }
        
        public PutScoreIntoTableWithPicRequest(CloudServer.KniffelService.PutScoreIntoTableWithPicRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableWithPicRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string table;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string picurl;
        
        public PutScoreIntoTableWithPicRequestBody() {
        }
        
        public PutScoreIntoTableWithPicRequestBody(string UserName, string Pass, string Score, string table, string picurl) {
            this.UserName = UserName;
            this.Pass = Pass;
            this.Score = Score;
            this.table = table;
            this.picurl = picurl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableWithPicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTableWithPicResponse", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.PutScoreIntoTableWithPicResponseBody Body;
        
        public PutScoreIntoTableWithPicResponse() {
        }
        
        public PutScoreIntoTableWithPicResponse(CloudServer.KniffelService.PutScoreIntoTableWithPicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableWithPicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PutScoreIntoTableWithPicResult;
        
        public PutScoreIntoTableWithPicResponseBody() {
        }
        
        public PutScoreIntoTableWithPicResponseBody(bool PutScoreIntoTableWithPicResult) {
            this.PutScoreIntoTableWithPicResult = PutScoreIntoTableWithPicResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableWithPicPureNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTableWithPicPureName", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameRequestBody Body;
        
        public PutScoreIntoTableWithPicPureNameRequest() {
        }
        
        public PutScoreIntoTableWithPicPureNameRequest(CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableWithPicPureNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string table;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string picurl;
        
        public PutScoreIntoTableWithPicPureNameRequestBody() {
        }
        
        public PutScoreIntoTableWithPicPureNameRequestBody(string UserName, string Pass, string Score, string table, string picurl) {
            this.UserName = UserName;
            this.Pass = Pass;
            this.Score = Score;
            this.table = table;
            this.picurl = picurl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutScoreIntoTableWithPicPureNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutScoreIntoTableWithPicPureNameResponse", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameResponseBody Body;
        
        public PutScoreIntoTableWithPicPureNameResponse() {
        }
        
        public PutScoreIntoTableWithPicPureNameResponse(CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutScoreIntoTableWithPicPureNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool PutScoreIntoTableWithPicPureNameResult;
        
        public PutScoreIntoTableWithPicPureNameResponseBody() {
        }
        
        public PutScoreIntoTableWithPicPureNameResponseBody(bool PutScoreIntoTableWithPicPureNameResult) {
            this.PutScoreIntoTableWithPicPureNameResult = PutScoreIntoTableWithPicPureNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutOnlineServerLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutOnlineServerLog", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.PutOnlineServerLogRequestBody Body;
        
        public PutOnlineServerLogRequest() {
        }
        
        public PutOnlineServerLogRequest(CloudServer.KniffelService.PutOnlineServerLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class PutOnlineServerLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string source;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message;
        
        public PutOnlineServerLogRequestBody() {
        }
        
        public PutOnlineServerLogRequestBody(string source, string message) {
            this.source = source;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PutOnlineServerLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PutOnlineServerLogResponse", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.PutOnlineServerLogResponseBody Body;
        
        public PutOnlineServerLogResponse() {
        }
        
        public PutOnlineServerLogResponse(CloudServer.KniffelService.PutOnlineServerLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PutOnlineServerLogResponseBody {
        
        public PutOnlineServerLogResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopPlayersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopPlayers", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.GetTopPlayersRequestBody Body;
        
        public GetTopPlayersRequest() {
        }
        
        public GetTopPlayersRequest(CloudServer.KniffelService.GetTopPlayersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetTopPlayersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rules;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public CloudServer.KniffelService.KniffelScore[] Players;
        
        public GetTopPlayersRequestBody() {
        }
        
        public GetTopPlayersRequestBody(string rules, CloudServer.KniffelService.KniffelScore[] Players) {
            this.rules = rules;
            this.Players = Players;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTopPlayersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTopPlayersResponse", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.GetTopPlayersResponseBody Body;
        
        public GetTopPlayersResponse() {
        }
        
        public GetTopPlayersResponse(CloudServer.KniffelService.GetTopPlayersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetTopPlayersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetTopPlayersResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public CloudServer.KniffelService.KniffelScore[] Players;
        
        public GetTopPlayersResponseBody() {
        }
        
        public GetTopPlayersResponseBody(bool GetTopPlayersResult, CloudServer.KniffelService.KniffelScore[] Players) {
            this.GetTopPlayersResult = GetTopPlayersResult;
            this.Players = Players;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChempionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChempion", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.GetChempionRequestBody Body;
        
        public GetChempionRequest() {
        }
        
        public GetChempionRequest(CloudServer.KniffelService.GetChempionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetChempionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rules;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetChempionRequestBody() {
        }
        
        public GetChempionRequestBody(string rules, string Name, string Score) {
            this.rules = rules;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChempionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetChempionResponse", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.GetChempionResponseBody Body;
        
        public GetChempionResponse() {
        }
        
        public GetChempionResponse(CloudServer.KniffelService.GetChempionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetChempionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetChempionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetChempionResponseBody() {
        }
        
        public GetChempionResponseBody(bool GetChempionResult, string Name, string Score) {
            this.GetChempionResult = GetChempionResult;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastWeekChempionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastWeekChempion", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.GetLastWeekChempionRequestBody Body;
        
        public GetLastWeekChempionRequest() {
        }
        
        public GetLastWeekChempionRequest(CloudServer.KniffelService.GetLastWeekChempionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetLastWeekChempionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rules;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetLastWeekChempionRequestBody() {
        }
        
        public GetLastWeekChempionRequestBody(string rules, string Name, string Score) {
            this.rules = rules;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastWeekChempionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastWeekChempionResponse", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.GetLastWeekChempionResponseBody Body;
        
        public GetLastWeekChempionResponse() {
        }
        
        public GetLastWeekChempionResponse(CloudServer.KniffelService.GetLastWeekChempionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetLastWeekChempionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetLastWeekChempionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetLastWeekChempionResponseBody() {
        }
        
        public GetLastWeekChempionResponseBody(bool GetLastWeekChempionResult, string Name, string Score) {
            this.GetLastWeekChempionResult = GetLastWeekChempionResult;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastDayChempionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastDayChempion", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.GetLastDayChempionRequestBody Body;
        
        public GetLastDayChempionRequest() {
        }
        
        public GetLastDayChempionRequest(CloudServer.KniffelService.GetLastDayChempionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetLastDayChempionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rules;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetLastDayChempionRequestBody() {
        }
        
        public GetLastDayChempionRequestBody(string rules, string Name, string Score) {
            this.rules = rules;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastDayChempionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastDayChempionResponse", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.GetLastDayChempionResponseBody Body;
        
        public GetLastDayChempionResponse() {
        }
        
        public GetLastDayChempionResponse(CloudServer.KniffelService.GetLastDayChempionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetLastDayChempionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetLastDayChempionResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Score;
        
        public GetLastDayChempionResponseBody() {
        }
        
        public GetLastDayChempionResponseBody(bool GetLastDayChempionResult, string Name, string Score) {
            this.GetLastDayChempionResult = GetLastDayChempionResult;
            this.Name = Name;
            this.Score = Score;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayersMagicsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayersMagics", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.GetPlayersMagicsRequestBody Body;
        
        public GetPlayersMagicsRequest() {
        }
        
        public GetPlayersMagicsRequest(CloudServer.KniffelService.GetPlayersMagicsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetPlayersMagicsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int rolls;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int manuals;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int resets;
        
        public GetPlayersMagicsRequestBody() {
        }
        
        public GetPlayersMagicsRequestBody(string username, string pass, int rolls, int manuals, int resets) {
            this.username = username;
            this.pass = pass;
            this.rolls = rolls;
            this.manuals = manuals;
            this.resets = resets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPlayersMagicsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPlayersMagicsResponse", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.GetPlayersMagicsResponseBody Body;
        
        public GetPlayersMagicsResponse() {
        }
        
        public GetPlayersMagicsResponse(CloudServer.KniffelService.GetPlayersMagicsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class GetPlayersMagicsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetPlayersMagicsResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int rolls;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int manuals;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int resets;
        
        public GetPlayersMagicsResponseBody() {
        }
        
        public GetPlayersMagicsResponseBody(bool GetPlayersMagicsResult, int rolls, int manuals, int resets) {
            this.GetPlayersMagicsResult = GetPlayersMagicsResult;
            this.rolls = rolls;
            this.manuals = manuals;
            this.resets = resets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPlayersMagicsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPlayersMagics", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.AddPlayersMagicsRequestBody Body;
        
        public AddPlayersMagicsRequest() {
        }
        
        public AddPlayersMagicsRequest(CloudServer.KniffelService.AddPlayersMagicsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class AddPlayersMagicsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rolls;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string manuals;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string resets;
        
        public AddPlayersMagicsRequestBody() {
        }
        
        public AddPlayersMagicsRequestBody(string username, string pass, string rolls, string manuals, string resets) {
            this.username = username;
            this.pass = pass;
            this.rolls = rolls;
            this.manuals = manuals;
            this.resets = resets;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPlayersMagicsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPlayersMagicsResponse", Namespace="http://www.sanet.com/", Order=0)]
        public CloudServer.KniffelService.AddPlayersMagicsResponseBody Body;
        
        public AddPlayersMagicsResponse() {
        }
        
        public AddPlayersMagicsResponse(CloudServer.KniffelService.AddPlayersMagicsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.sanet.com/")]
    public partial class AddPlayersMagicsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddPlayersMagicsResult;
        
        public AddPlayersMagicsResponseBody() {
        }
        
        public AddPlayersMagicsResponseBody(bool AddPlayersMagicsResult) {
            this.AddPlayersMagicsResult = AddPlayersMagicsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KniffelServiceSoapChannel : CloudServer.KniffelService.KniffelServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KniffelServiceSoapClient : System.ServiceModel.ClientBase<CloudServer.KniffelService.KniffelServiceSoap>, CloudServer.KniffelService.KniffelServiceSoap {
        
        public KniffelServiceSoapClient() {
        }
        
        public KniffelServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KniffelServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KniffelServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KniffelServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServer.KniffelService.PutScoreResponse CloudServer.KniffelService.KniffelServiceSoap.PutScore(CloudServer.KniffelService.PutScoreRequest request) {
            return base.Channel.PutScore(request);
        }
        
        public bool PutScore(string UserName, string Pass, string Score) {
            CloudServer.KniffelService.PutScoreRequest inValue = new CloudServer.KniffelService.PutScoreRequest();
            inValue.Body = new CloudServer.KniffelService.PutScoreRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pass = Pass;
            inValue.Body.Score = Score;
            CloudServer.KniffelService.PutScoreResponse retVal = ((CloudServer.KniffelService.KniffelServiceSoap)(this)).PutScore(inValue);
            return retVal.Body.PutScoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudServer.KniffelService.PutScoreResponse> CloudServer.KniffelService.KniffelServiceSoap.PutScoreAsync(CloudServer.KniffelService.PutScoreRequest request) {
            return base.Channel.PutScoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudServer.KniffelService.PutScoreResponse> PutScoreAsync(string UserName, string Pass, string Score) {
            CloudServer.KniffelService.PutScoreRequest inValue = new CloudServer.KniffelService.PutScoreRequest();
            inValue.Body = new CloudServer.KniffelService.PutScoreRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pass = Pass;
            inValue.Body.Score = Score;
            return ((CloudServer.KniffelService.KniffelServiceSoap)(this)).PutScoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServer.KniffelService.PutScoreIntoTableResponse CloudServer.KniffelService.KniffelServiceSoap.PutScoreIntoTable(CloudServer.KniffelService.PutScoreIntoTableRequest request) {
            return base.Channel.PutScoreIntoTable(request);
        }
        
        public bool PutScoreIntoTable(string UserName, string Pass, string Score, string table) {
            CloudServer.KniffelService.PutScoreIntoTableRequest inValue = new CloudServer.KniffelService.PutScoreIntoTableRequest();
            inValue.Body = new CloudServer.KniffelService.PutScoreIntoTableRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pass = Pass;
            inValue.Body.Score = Score;
            inValue.Body.table = table;
            CloudServer.KniffelService.PutScoreIntoTableResponse retVal = ((CloudServer.KniffelService.KniffelServiceSoap)(this)).PutScoreIntoTable(inValue);
            return retVal.Body.PutScoreIntoTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudServer.KniffelService.PutScoreIntoTableResponse> CloudServer.KniffelService.KniffelServiceSoap.PutScoreIntoTableAsync(CloudServer.KniffelService.PutScoreIntoTableRequest request) {
            return base.Channel.PutScoreIntoTableAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudServer.KniffelService.PutScoreIntoTableResponse> PutScoreIntoTableAsync(string UserName, string Pass, string Score, string table) {
            CloudServer.KniffelService.PutScoreIntoTableRequest inValue = new CloudServer.KniffelService.PutScoreIntoTableRequest();
            inValue.Body = new CloudServer.KniffelService.PutScoreIntoTableRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pass = Pass;
            inValue.Body.Score = Score;
            inValue.Body.table = table;
            return ((CloudServer.KniffelService.KniffelServiceSoap)(this)).PutScoreIntoTableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServer.KniffelService.PutScoreIntoTableWithPicResponse CloudServer.KniffelService.KniffelServiceSoap.PutScoreIntoTableWithPic(CloudServer.KniffelService.PutScoreIntoTableWithPicRequest request) {
            return base.Channel.PutScoreIntoTableWithPic(request);
        }
        
        public bool PutScoreIntoTableWithPic(string UserName, string Pass, string Score, string table, string picurl) {
            CloudServer.KniffelService.PutScoreIntoTableWithPicRequest inValue = new CloudServer.KniffelService.PutScoreIntoTableWithPicRequest();
            inValue.Body = new CloudServer.KniffelService.PutScoreIntoTableWithPicRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pass = Pass;
            inValue.Body.Score = Score;
            inValue.Body.table = table;
            inValue.Body.picurl = picurl;
            CloudServer.KniffelService.PutScoreIntoTableWithPicResponse retVal = ((CloudServer.KniffelService.KniffelServiceSoap)(this)).PutScoreIntoTableWithPic(inValue);
            return retVal.Body.PutScoreIntoTableWithPicResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudServer.KniffelService.PutScoreIntoTableWithPicResponse> CloudServer.KniffelService.KniffelServiceSoap.PutScoreIntoTableWithPicAsync(CloudServer.KniffelService.PutScoreIntoTableWithPicRequest request) {
            return base.Channel.PutScoreIntoTableWithPicAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudServer.KniffelService.PutScoreIntoTableWithPicResponse> PutScoreIntoTableWithPicAsync(string UserName, string Pass, string Score, string table, string picurl) {
            CloudServer.KniffelService.PutScoreIntoTableWithPicRequest inValue = new CloudServer.KniffelService.PutScoreIntoTableWithPicRequest();
            inValue.Body = new CloudServer.KniffelService.PutScoreIntoTableWithPicRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pass = Pass;
            inValue.Body.Score = Score;
            inValue.Body.table = table;
            inValue.Body.picurl = picurl;
            return ((CloudServer.KniffelService.KniffelServiceSoap)(this)).PutScoreIntoTableWithPicAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameResponse CloudServer.KniffelService.KniffelServiceSoap.PutScoreIntoTableWithPicPureName(CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameRequest request) {
            return base.Channel.PutScoreIntoTableWithPicPureName(request);
        }
        
        public bool PutScoreIntoTableWithPicPureName(string UserName, string Pass, string Score, string table, string picurl) {
            CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameRequest inValue = new CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameRequest();
            inValue.Body = new CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pass = Pass;
            inValue.Body.Score = Score;
            inValue.Body.table = table;
            inValue.Body.picurl = picurl;
            CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameResponse retVal = ((CloudServer.KniffelService.KniffelServiceSoap)(this)).PutScoreIntoTableWithPicPureName(inValue);
            return retVal.Body.PutScoreIntoTableWithPicPureNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameResponse> CloudServer.KniffelService.KniffelServiceSoap.PutScoreIntoTableWithPicPureNameAsync(CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameRequest request) {
            return base.Channel.PutScoreIntoTableWithPicPureNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameResponse> PutScoreIntoTableWithPicPureNameAsync(string UserName, string Pass, string Score, string table, string picurl) {
            CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameRequest inValue = new CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameRequest();
            inValue.Body = new CloudServer.KniffelService.PutScoreIntoTableWithPicPureNameRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Pass = Pass;
            inValue.Body.Score = Score;
            inValue.Body.table = table;
            inValue.Body.picurl = picurl;
            return ((CloudServer.KniffelService.KniffelServiceSoap)(this)).PutScoreIntoTableWithPicPureNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServer.KniffelService.PutOnlineServerLogResponse CloudServer.KniffelService.KniffelServiceSoap.PutOnlineServerLog(CloudServer.KniffelService.PutOnlineServerLogRequest request) {
            return base.Channel.PutOnlineServerLog(request);
        }
        
        public void PutOnlineServerLog(string source, string message) {
            CloudServer.KniffelService.PutOnlineServerLogRequest inValue = new CloudServer.KniffelService.PutOnlineServerLogRequest();
            inValue.Body = new CloudServer.KniffelService.PutOnlineServerLogRequestBody();
            inValue.Body.source = source;
            inValue.Body.message = message;
            CloudServer.KniffelService.PutOnlineServerLogResponse retVal = ((CloudServer.KniffelService.KniffelServiceSoap)(this)).PutOnlineServerLog(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudServer.KniffelService.PutOnlineServerLogResponse> CloudServer.KniffelService.KniffelServiceSoap.PutOnlineServerLogAsync(CloudServer.KniffelService.PutOnlineServerLogRequest request) {
            return base.Channel.PutOnlineServerLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudServer.KniffelService.PutOnlineServerLogResponse> PutOnlineServerLogAsync(string source, string message) {
            CloudServer.KniffelService.PutOnlineServerLogRequest inValue = new CloudServer.KniffelService.PutOnlineServerLogRequest();
            inValue.Body = new CloudServer.KniffelService.PutOnlineServerLogRequestBody();
            inValue.Body.source = source;
            inValue.Body.message = message;
            return ((CloudServer.KniffelService.KniffelServiceSoap)(this)).PutOnlineServerLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServer.KniffelService.GetTopPlayersResponse CloudServer.KniffelService.KniffelServiceSoap.GetTopPlayers(CloudServer.KniffelService.GetTopPlayersRequest request) {
            return base.Channel.GetTopPlayers(request);
        }
        
        public bool GetTopPlayers(string rules, ref CloudServer.KniffelService.KniffelScore[] Players) {
            CloudServer.KniffelService.GetTopPlayersRequest inValue = new CloudServer.KniffelService.GetTopPlayersRequest();
            inValue.Body = new CloudServer.KniffelService.GetTopPlayersRequestBody();
            inValue.Body.rules = rules;
            inValue.Body.Players = Players;
            CloudServer.KniffelService.GetTopPlayersResponse retVal = ((CloudServer.KniffelService.KniffelServiceSoap)(this)).GetTopPlayers(inValue);
            Players = retVal.Body.Players;
            return retVal.Body.GetTopPlayersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudServer.KniffelService.GetTopPlayersResponse> CloudServer.KniffelService.KniffelServiceSoap.GetTopPlayersAsync(CloudServer.KniffelService.GetTopPlayersRequest request) {
            return base.Channel.GetTopPlayersAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudServer.KniffelService.GetTopPlayersResponse> GetTopPlayersAsync(string rules, CloudServer.KniffelService.KniffelScore[] Players) {
            CloudServer.KniffelService.GetTopPlayersRequest inValue = new CloudServer.KniffelService.GetTopPlayersRequest();
            inValue.Body = new CloudServer.KniffelService.GetTopPlayersRequestBody();
            inValue.Body.rules = rules;
            inValue.Body.Players = Players;
            return ((CloudServer.KniffelService.KniffelServiceSoap)(this)).GetTopPlayersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServer.KniffelService.GetChempionResponse CloudServer.KniffelService.KniffelServiceSoap.GetChempion(CloudServer.KniffelService.GetChempionRequest request) {
            return base.Channel.GetChempion(request);
        }
        
        public bool GetChempion(string rules, ref string Name, ref string Score) {
            CloudServer.KniffelService.GetChempionRequest inValue = new CloudServer.KniffelService.GetChempionRequest();
            inValue.Body = new CloudServer.KniffelService.GetChempionRequestBody();
            inValue.Body.rules = rules;
            inValue.Body.Name = Name;
            inValue.Body.Score = Score;
            CloudServer.KniffelService.GetChempionResponse retVal = ((CloudServer.KniffelService.KniffelServiceSoap)(this)).GetChempion(inValue);
            Name = retVal.Body.Name;
            Score = retVal.Body.Score;
            return retVal.Body.GetChempionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudServer.KniffelService.GetChempionResponse> CloudServer.KniffelService.KniffelServiceSoap.GetChempionAsync(CloudServer.KniffelService.GetChempionRequest request) {
            return base.Channel.GetChempionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudServer.KniffelService.GetChempionResponse> GetChempionAsync(string rules, string Name, string Score) {
            CloudServer.KniffelService.GetChempionRequest inValue = new CloudServer.KniffelService.GetChempionRequest();
            inValue.Body = new CloudServer.KniffelService.GetChempionRequestBody();
            inValue.Body.rules = rules;
            inValue.Body.Name = Name;
            inValue.Body.Score = Score;
            return ((CloudServer.KniffelService.KniffelServiceSoap)(this)).GetChempionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServer.KniffelService.GetLastWeekChempionResponse CloudServer.KniffelService.KniffelServiceSoap.GetLastWeekChempion(CloudServer.KniffelService.GetLastWeekChempionRequest request) {
            return base.Channel.GetLastWeekChempion(request);
        }
        
        public bool GetLastWeekChempion(string rules, ref string Name, ref string Score) {
            CloudServer.KniffelService.GetLastWeekChempionRequest inValue = new CloudServer.KniffelService.GetLastWeekChempionRequest();
            inValue.Body = new CloudServer.KniffelService.GetLastWeekChempionRequestBody();
            inValue.Body.rules = rules;
            inValue.Body.Name = Name;
            inValue.Body.Score = Score;
            CloudServer.KniffelService.GetLastWeekChempionResponse retVal = ((CloudServer.KniffelService.KniffelServiceSoap)(this)).GetLastWeekChempion(inValue);
            Name = retVal.Body.Name;
            Score = retVal.Body.Score;
            return retVal.Body.GetLastWeekChempionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudServer.KniffelService.GetLastWeekChempionResponse> CloudServer.KniffelService.KniffelServiceSoap.GetLastWeekChempionAsync(CloudServer.KniffelService.GetLastWeekChempionRequest request) {
            return base.Channel.GetLastWeekChempionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudServer.KniffelService.GetLastWeekChempionResponse> GetLastWeekChempionAsync(string rules, string Name, string Score) {
            CloudServer.KniffelService.GetLastWeekChempionRequest inValue = new CloudServer.KniffelService.GetLastWeekChempionRequest();
            inValue.Body = new CloudServer.KniffelService.GetLastWeekChempionRequestBody();
            inValue.Body.rules = rules;
            inValue.Body.Name = Name;
            inValue.Body.Score = Score;
            return ((CloudServer.KniffelService.KniffelServiceSoap)(this)).GetLastWeekChempionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServer.KniffelService.GetLastDayChempionResponse CloudServer.KniffelService.KniffelServiceSoap.GetLastDayChempion(CloudServer.KniffelService.GetLastDayChempionRequest request) {
            return base.Channel.GetLastDayChempion(request);
        }
        
        public bool GetLastDayChempion(string rules, ref string Name, ref string Score) {
            CloudServer.KniffelService.GetLastDayChempionRequest inValue = new CloudServer.KniffelService.GetLastDayChempionRequest();
            inValue.Body = new CloudServer.KniffelService.GetLastDayChempionRequestBody();
            inValue.Body.rules = rules;
            inValue.Body.Name = Name;
            inValue.Body.Score = Score;
            CloudServer.KniffelService.GetLastDayChempionResponse retVal = ((CloudServer.KniffelService.KniffelServiceSoap)(this)).GetLastDayChempion(inValue);
            Name = retVal.Body.Name;
            Score = retVal.Body.Score;
            return retVal.Body.GetLastDayChempionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudServer.KniffelService.GetLastDayChempionResponse> CloudServer.KniffelService.KniffelServiceSoap.GetLastDayChempionAsync(CloudServer.KniffelService.GetLastDayChempionRequest request) {
            return base.Channel.GetLastDayChempionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudServer.KniffelService.GetLastDayChempionResponse> GetLastDayChempionAsync(string rules, string Name, string Score) {
            CloudServer.KniffelService.GetLastDayChempionRequest inValue = new CloudServer.KniffelService.GetLastDayChempionRequest();
            inValue.Body = new CloudServer.KniffelService.GetLastDayChempionRequestBody();
            inValue.Body.rules = rules;
            inValue.Body.Name = Name;
            inValue.Body.Score = Score;
            return ((CloudServer.KniffelService.KniffelServiceSoap)(this)).GetLastDayChempionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServer.KniffelService.GetPlayersMagicsResponse CloudServer.KniffelService.KniffelServiceSoap.GetPlayersMagics(CloudServer.KniffelService.GetPlayersMagicsRequest request) {
            return base.Channel.GetPlayersMagics(request);
        }
        
        public bool GetPlayersMagics(string username, string pass, ref int rolls, ref int manuals, ref int resets) {
            CloudServer.KniffelService.GetPlayersMagicsRequest inValue = new CloudServer.KniffelService.GetPlayersMagicsRequest();
            inValue.Body = new CloudServer.KniffelService.GetPlayersMagicsRequestBody();
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.rolls = rolls;
            inValue.Body.manuals = manuals;
            inValue.Body.resets = resets;
            CloudServer.KniffelService.GetPlayersMagicsResponse retVal = ((CloudServer.KniffelService.KniffelServiceSoap)(this)).GetPlayersMagics(inValue);
            rolls = retVal.Body.rolls;
            manuals = retVal.Body.manuals;
            resets = retVal.Body.resets;
            return retVal.Body.GetPlayersMagicsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudServer.KniffelService.GetPlayersMagicsResponse> CloudServer.KniffelService.KniffelServiceSoap.GetPlayersMagicsAsync(CloudServer.KniffelService.GetPlayersMagicsRequest request) {
            return base.Channel.GetPlayersMagicsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudServer.KniffelService.GetPlayersMagicsResponse> GetPlayersMagicsAsync(string username, string pass, int rolls, int manuals, int resets) {
            CloudServer.KniffelService.GetPlayersMagicsRequest inValue = new CloudServer.KniffelService.GetPlayersMagicsRequest();
            inValue.Body = new CloudServer.KniffelService.GetPlayersMagicsRequestBody();
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.rolls = rolls;
            inValue.Body.manuals = manuals;
            inValue.Body.resets = resets;
            return ((CloudServer.KniffelService.KniffelServiceSoap)(this)).GetPlayersMagicsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudServer.KniffelService.AddPlayersMagicsResponse CloudServer.KniffelService.KniffelServiceSoap.AddPlayersMagics(CloudServer.KniffelService.AddPlayersMagicsRequest request) {
            return base.Channel.AddPlayersMagics(request);
        }
        
        public bool AddPlayersMagics(string username, string pass, string rolls, string manuals, string resets) {
            CloudServer.KniffelService.AddPlayersMagicsRequest inValue = new CloudServer.KniffelService.AddPlayersMagicsRequest();
            inValue.Body = new CloudServer.KniffelService.AddPlayersMagicsRequestBody();
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.rolls = rolls;
            inValue.Body.manuals = manuals;
            inValue.Body.resets = resets;
            CloudServer.KniffelService.AddPlayersMagicsResponse retVal = ((CloudServer.KniffelService.KniffelServiceSoap)(this)).AddPlayersMagics(inValue);
            return retVal.Body.AddPlayersMagicsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudServer.KniffelService.AddPlayersMagicsResponse> CloudServer.KniffelService.KniffelServiceSoap.AddPlayersMagicsAsync(CloudServer.KniffelService.AddPlayersMagicsRequest request) {
            return base.Channel.AddPlayersMagicsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudServer.KniffelService.AddPlayersMagicsResponse> AddPlayersMagicsAsync(string username, string pass, string rolls, string manuals, string resets) {
            CloudServer.KniffelService.AddPlayersMagicsRequest inValue = new CloudServer.KniffelService.AddPlayersMagicsRequest();
            inValue.Body = new CloudServer.KniffelService.AddPlayersMagicsRequestBody();
            inValue.Body.username = username;
            inValue.Body.pass = pass;
            inValue.Body.rolls = rolls;
            inValue.Body.manuals = manuals;
            inValue.Body.resets = resets;
            return ((CloudServer.KniffelService.KniffelServiceSoap)(this)).AddPlayersMagicsAsync(inValue);
        }
    }
}
