'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

'
'This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
'
Namespace KniffelGameService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DuplexMessage", [Namespace]:="http://samples.microsoft.com/silverlight2/duplex"),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.DisconnectMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.ConnectMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.GeneralError)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.EncrytValueMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.ClientDisconnectedMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.ClientConnectedMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.ChatMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.ConnectGameRoomMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.JoinSessionMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.GameStatusMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.GameOverMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.JoinSessionServerMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.ApplyScoreMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.DoMoveMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.DoRollMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.DieFixedMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.PlayerIsReadyMessage)),  _
     System.Runtime.Serialization.KnownTypeAttribute(GetType(KniffelGameService.CreateGameRoomMessage))>  _
    Partial Public Class DuplexMessage
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DisconnectMessage", [Namespace]:="http://samples.microsoft.com/silverlight2/duplex")>  _
    Partial Public Class DisconnectMessage
        Inherits KniffelGameService.DuplexMessage
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ConnectMessage", [Namespace]:="http://samples.microsoft.com/silverlight2/duplex")>  _
    Partial Public Class ConnectMessage
        Inherits KniffelGameService.DuplexMessage
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GeneralError", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class GeneralError
        Inherits KniffelGameService.DuplexMessage
        
        Private ErrorMessageField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.ErrorMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorMessageField, value) <> true) Then
                    Me.ErrorMessageField = value
                    Me.RaisePropertyChanged("ErrorMessage")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="EncrytValueMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class EncrytValueMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private ValueField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Value() As String
            Get
                Return Me.ValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValueField, value) <> true) Then
                    Me.ValueField = value
                    Me.RaisePropertyChanged("Value")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ClientDisconnectedMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class ClientDisconnectedMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private UsernameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ClientConnectedMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class ClientConnectedMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private AllGamesField As String
        
        Private AllPlayersField As String
        
        Private UsernameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AllGames() As String
            Get
                Return Me.AllGamesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AllGamesField, value) <> true) Then
                    Me.AllGamesField = value
                    Me.RaisePropertyChanged("AllGames")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AllPlayers() As String
            Get
                Return Me.AllPlayersField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AllPlayersField, value) <> true) Then
                    Me.AllPlayersField = value
                    Me.RaisePropertyChanged("AllPlayers")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ChatMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class ChatMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private FromIDField As String
        
        Private GameIDField As Integer
        
        Private MessageField As String
        
        Private ToIDField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FromID() As String
            Get
                Return Me.FromIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FromIDField, value) <> true) Then
                    Me.FromIDField = value
                    Me.RaisePropertyChanged("FromID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GameID() As Integer
            Get
                Return Me.GameIDField
            End Get
            Set
                If (Me.GameIDField.Equals(value) <> true) Then
                    Me.GameIDField = value
                    Me.RaisePropertyChanged("GameID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Message() As String
            Get
                Return Me.MessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MessageField, value) <> true) Then
                    Me.MessageField = value
                    Me.RaisePropertyChanged("Message")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ToID() As String
            Get
                Return Me.ToIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ToIDField, value) <> true) Then
                    Me.ToIDField = value
                    Me.RaisePropertyChanged("ToID")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ConnectGameRoomMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class ConnectGameRoomMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private GameIdField As Integer
        
        Private GameTableField As String
        
        Private OldGameIdField As Integer
        
        Private RulesField As Integer
        
        Private UsernameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GameId() As Integer
            Get
                Return Me.GameIdField
            End Get
            Set
                If (Me.GameIdField.Equals(value) <> true) Then
                    Me.GameIdField = value
                    Me.RaisePropertyChanged("GameId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GameTable() As String
            Get
                Return Me.GameTableField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GameTableField, value) <> true) Then
                    Me.GameTableField = value
                    Me.RaisePropertyChanged("GameTable")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OldGameId() As Integer
            Get
                Return Me.OldGameIdField
            End Get
            Set
                If (Me.OldGameIdField.Equals(value) <> true) Then
                    Me.OldGameIdField = value
                    Me.RaisePropertyChanged("OldGameId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Rules() As Integer
            Get
                Return Me.RulesField
            End Get
            Set
                If (Me.RulesField.Equals(value) <> true) Then
                    Me.RulesField = value
                    Me.RaisePropertyChanged("Rules")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="JoinSessionMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class JoinSessionMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private UserPassField As String
        
        Private UsernameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserPass() As String
            Get
                Return Me.UserPassField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UserPassField, value) <> true) Then
                    Me.UserPassField = value
                    Me.RaisePropertyChanged("UserPass")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GameStatusMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class GameStatusMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private GameIdField As Integer
        
        Private IsPlayingField As Boolean
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GameId() As Integer
            Get
                Return Me.GameIdField
            End Get
            Set
                If (Me.GameIdField.Equals(value) <> true) Then
                    Me.GameIdField = value
                    Me.RaisePropertyChanged("GameId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsPlaying() As Boolean
            Get
                Return Me.IsPlayingField
            End Get
            Set
                If (Me.IsPlayingField.Equals(value) <> true) Then
                    Me.IsPlayingField = value
                    Me.RaisePropertyChanged("IsPlaying")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="GameOverMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class GameOverMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private GameIdField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GameId() As Integer
            Get
                Return Me.GameIdField
            End Get
            Set
                If (Me.GameIdField.Equals(value) <> true) Then
                    Me.GameIdField = value
                    Me.RaisePropertyChanged("GameId")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="JoinSessionServerMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class JoinSessionServerMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private ENameField As String
        
        Private EPasswordField As String
        
        Private FailedField As Boolean
        
        Private IDField As String
        
        Private NameField As String
        
        Private PasswordField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EName() As String
            Get
                Return Me.ENameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ENameField, value) <> true) Then
                    Me.ENameField = value
                    Me.RaisePropertyChanged("EName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EPassword() As String
            Get
                Return Me.EPasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EPasswordField, value) <> true) Then
                    Me.EPasswordField = value
                    Me.RaisePropertyChanged("EPassword")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Failed() As Boolean
            Get
                Return Me.FailedField
            End Get
            Set
                If (Me.FailedField.Equals(value) <> true) Then
                    Me.FailedField = value
                    Me.RaisePropertyChanged("Failed")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As String
            Get
                Return Me.IDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IDField, value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ApplyScoreMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class ApplyScoreMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private GameIdField As Integer
        
        Private HaveBonusField As Boolean
        
        Private MoveField As Integer
        
        Private ScoreTypeField As Integer
        
        Private ScoreValueField As Integer
        
        Private UsernameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GameId() As Integer
            Get
                Return Me.GameIdField
            End Get
            Set
                If (Me.GameIdField.Equals(value) <> true) Then
                    Me.GameIdField = value
                    Me.RaisePropertyChanged("GameId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property HaveBonus() As Boolean
            Get
                Return Me.HaveBonusField
            End Get
            Set
                If (Me.HaveBonusField.Equals(value) <> true) Then
                    Me.HaveBonusField = value
                    Me.RaisePropertyChanged("HaveBonus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Move() As Integer
            Get
                Return Me.MoveField
            End Get
            Set
                If (Me.MoveField.Equals(value) <> true) Then
                    Me.MoveField = value
                    Me.RaisePropertyChanged("Move")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ScoreType() As Integer
            Get
                Return Me.ScoreTypeField
            End Get
            Set
                If (Me.ScoreTypeField.Equals(value) <> true) Then
                    Me.ScoreTypeField = value
                    Me.RaisePropertyChanged("ScoreType")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ScoreValue() As Integer
            Get
                Return Me.ScoreValueField
            End Get
            Set
                If (Me.ScoreValueField.Equals(value) <> true) Then
                    Me.ScoreValueField = value
                    Me.RaisePropertyChanged("ScoreValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DoMoveMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class DoMoveMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private GameIdField As Integer
        
        Private MoveField As Integer
        
        Private UsernameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GameId() As Integer
            Get
                Return Me.GameIdField
            End Get
            Set
                If (Me.GameIdField.Equals(value) <> true) Then
                    Me.GameIdField = value
                    Me.RaisePropertyChanged("GameId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Move() As Integer
            Get
                Return Me.MoveField
            End Get
            Set
                If (Me.MoveField.Equals(value) <> true) Then
                    Me.MoveField = value
                    Me.RaisePropertyChanged("Move")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DoRollMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class DoRollMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private GameIdField As Integer
        
        Private ValueField As System.Collections.ObjectModel.ObservableCollection(Of Integer)
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GameId() As Integer
            Get
                Return Me.GameIdField
            End Get
            Set
                If (Me.GameIdField.Equals(value) <> true) Then
                    Me.GameIdField = value
                    Me.RaisePropertyChanged("GameId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Value() As System.Collections.ObjectModel.ObservableCollection(Of Integer)
            Get
                Return Me.ValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ValueField, value) <> true) Then
                    Me.ValueField = value
                    Me.RaisePropertyChanged("Value")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DieFixedMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class DieFixedMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private FixedField As Boolean
        
        Private GameIdField As Integer
        
        Private UsernameField As String
        
        Private ValueField As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Fixed() As Boolean
            Get
                Return Me.FixedField
            End Get
            Set
                If (Me.FixedField.Equals(value) <> true) Then
                    Me.FixedField = value
                    Me.RaisePropertyChanged("Fixed")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GameId() As Integer
            Get
                Return Me.GameIdField
            End Get
            Set
                If (Me.GameIdField.Equals(value) <> true) Then
                    Me.GameIdField = value
                    Me.RaisePropertyChanged("GameId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Value() As Integer
            Get
                Return Me.ValueField
            End Get
            Set
                If (Me.ValueField.Equals(value) <> true) Then
                    Me.ValueField = value
                    Me.RaisePropertyChanged("Value")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PlayerIsReadyMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class PlayerIsReadyMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private GameIdField As Integer
        
        Private UsernameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GameId() As Integer
            Get
                Return Me.GameIdField
            End Get
            Set
                If (Me.GameIdField.Equals(value) <> true) Then
                    Me.GameIdField = value
                    Me.RaisePropertyChanged("GameId")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CreateGameRoomMessage", [Namespace]:="http://schemas.datacontract.org/2004/07/Kniffel.Web")>  _
    Partial Public Class CreateGameRoomMessage
        Inherits KniffelGameService.DuplexMessage
        
        Private RulesField As Integer
        
        Private UsernameField As String
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Rules() As Integer
            Get
                Return Me.RulesField
            End Get
            Set
                If (Me.RulesField.Equals(value) <> true) Then
                    Me.RulesField = value
                    Me.RaisePropertyChanged("Rules")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsernameField, value) <> true) Then
                    Me.UsernameField = value
                    Me.RaisePropertyChanged("Username")
                End If
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="KniffelGameService.DuplexService", CallbackContract:=GetType(KniffelGameService.DuplexServiceCallback))>  _
    Public Interface DuplexService
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, AsyncPattern:=true, Action:="http://tempuri.org/DuplexService/SendToService")>  _
        Function BeginSendToService(ByVal request As KniffelGameService.SendToService, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Sub EndSendToService(ByVal result As System.IAsyncResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface DuplexServiceCallback
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/DuplexService/SendToClient")>  _
        Sub SendToClient(ByVal request As KniffelGameService.SendToClient)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="SendToService", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class SendToService
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public msg As KniffelGameService.DuplexMessage
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal msg As KniffelGameService.DuplexMessage)
            MyBase.New
            Me.msg = msg
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="SendToClient", WrapperNamespace:="http://tempuri.org/", IsWrapped:=true)>  _
    Partial Public Class SendToClient
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public msg As KniffelGameService.DuplexMessage
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal msg As KniffelGameService.DuplexMessage)
            MyBase.New
            Me.msg = msg
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface DuplexServiceChannel
        Inherits KniffelGameService.DuplexService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DuplexServiceClient
        Inherits System.ServiceModel.DuplexClientBase(Of KniffelGameService.DuplexService)
        Implements KniffelGameService.DuplexService
        
        Private onBeginSendToServiceDelegate As BeginOperationDelegate
        
        Private onEndSendToServiceDelegate As EndOperationDelegate
        
        Private onSendToServiceCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private useGeneratedCallback As Boolean
        
        Private onBeginOpenDelegate As BeginOperationDelegate
        
        Private onEndOpenDelegate As EndOperationDelegate
        
        Private onOpenCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginCloseDelegate As BeginOperationDelegate
        
        Private onEndCloseDelegate As EndOperationDelegate
        
        Private onCloseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext)
            MyBase.New(callbackInstance)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String)
            MyBase.New(callbackInstance, endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, binding, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            Me.New(New DuplexServiceClientCallback(), endpointConfigurationName)
        End Sub
        
        Private Sub New(ByVal callbackImpl As DuplexServiceClientCallback, ByVal endpointConfigurationName As String)
            Me.New(New System.ServiceModel.InstanceContext(callbackImpl), endpointConfigurationName)
            useGeneratedCallback = true
            callbackImpl.Initialize(Me)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            Me.New(New DuplexServiceClientCallback(), binding, remoteAddress)
        End Sub
        
        Private Sub New(ByVal callbackImpl As DuplexServiceClientCallback, ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            Me.New(New System.ServiceModel.InstanceContext(callbackImpl), binding, remoteAddress)
            useGeneratedCallback = true
            callbackImpl.Initialize(Me)
        End Sub
        
        Public Sub New()
            Me.New(New DuplexServiceClientCallback())
        End Sub
        
        Private Sub New(ByVal callbackImpl As DuplexServiceClientCallback)
            Me.New(New System.ServiceModel.InstanceContext(callbackImpl))
            useGeneratedCallback = true
            callbackImpl.Initialize(Me)
        End Sub
        
        Public Property CookieContainer() As System.Net.CookieContainer
            Get
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    Return httpCookieContainerManager.CookieContainer
                Else
                    Return Nothing
                End If
            End Get
            Set
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    httpCookieContainerManager.CookieContainer = value
                Else
                    Throw New System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC"& _ 
                            "ookieContainerBindingElement.")
                End If
            End Set
        End Property
        
        Public Event SendToServiceCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event SendToClientReceived As System.EventHandler(Of SendToClientReceivedEventArgs)
        
        Public Event OpenCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event CloseCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelGameService_DuplexService_BeginSendToService(ByVal request As KniffelGameService.SendToService, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelGameService.DuplexService.BeginSendToService
            Return MyBase.Channel.BeginSendToService(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Sub KniffelGameService_DuplexService_EndSendToService(ByVal result As System.IAsyncResult) Implements KniffelGameService.DuplexService.EndSendToService
            MyBase.Channel.EndSendToService(result)
        End Sub
        
        Private Function OnBeginSendToService(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Me.VerifyCallbackEvents
            Dim request As KniffelGameService.SendToService = CType(inValues(0),KniffelGameService.SendToService)
            Return CType(Me,KniffelGameService.DuplexService).BeginSendToService(request, callback, asyncState)
        End Function
        
        Private Function OnEndSendToService(ByVal result As System.IAsyncResult) As Object()
            CType(Me,KniffelGameService.DuplexService).EndSendToService(result)
            Return Nothing
        End Function
        
        Private Sub OnSendToServiceCompleted(ByVal state As Object)
            If (Not (Me.SendToServiceCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent SendToServiceCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub SendToServiceAsync(ByVal request As KniffelGameService.SendToService)
            Me.SendToServiceAsync(request, Nothing)
        End Sub
        
        Public Overloads Sub SendToServiceAsync(ByVal request As KniffelGameService.SendToService, ByVal userState As Object)
            If (Me.onBeginSendToServiceDelegate Is Nothing) Then
                Me.onBeginSendToServiceDelegate = AddressOf Me.OnBeginSendToService
            End If
            If (Me.onEndSendToServiceDelegate Is Nothing) Then
                Me.onEndSendToServiceDelegate = AddressOf Me.OnEndSendToService
            End If
            If (Me.onSendToServiceCompletedDelegate Is Nothing) Then
                Me.onSendToServiceCompletedDelegate = AddressOf Me.OnSendToServiceCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSendToServiceDelegate, New Object() {request}, Me.onEndSendToServiceDelegate, Me.onSendToServiceCompletedDelegate, userState)
        End Sub
        
        Private Sub OnSendToClientReceived(ByVal state As Object)
            If (Not (Me.SendToClientReceivedEvent) Is Nothing) Then
                Dim results() As Object = CType(state,Object())
                RaiseEvent SendToClientReceived(Me, New SendToClientReceivedEventArgs(results, Nothing, false, Nothing))
            End If
        End Sub
        
        Private Sub VerifyCallbackEvents()
            If ((Me.useGeneratedCallback <> true)  _
                        AndAlso (Not (Me.SendToClientReceivedEvent) Is Nothing)) Then
                Throw New System.InvalidOperationException("Callback events cannot be used when the callback InstanceContext is specified. Pl"& _ 
                        "ease choose between specifying the callback InstanceContext or subscribing to th"& _ 
                        "e callback events.")
            End If
        End Sub
        
        Private Function OnBeginOpen(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Me.VerifyCallbackEvents
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(callback, asyncState)
        End Function
        
        Private Function OnEndOpen(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndOpen(result)
            Return Nothing
        End Function
        
        Private Sub OnOpenCompleted(ByVal state As Object)
            If (Not (Me.OpenCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent OpenCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub OpenAsync()
            Me.OpenAsync(Nothing)
        End Sub
        
        Public Overloads Sub OpenAsync(ByVal userState As Object)
            If (Me.onBeginOpenDelegate Is Nothing) Then
                Me.onBeginOpenDelegate = AddressOf Me.OnBeginOpen
            End If
            If (Me.onEndOpenDelegate Is Nothing) Then
                Me.onEndOpenDelegate = AddressOf Me.OnEndOpen
            End If
            If (Me.onOpenCompletedDelegate Is Nothing) Then
                Me.onOpenCompletedDelegate = AddressOf Me.OnOpenCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginOpenDelegate, Nothing, Me.onEndOpenDelegate, Me.onOpenCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginClose(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(callback, asyncState)
        End Function
        
        Private Function OnEndClose(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndClose(result)
            Return Nothing
        End Function
        
        Private Sub OnCloseCompleted(ByVal state As Object)
            If (Not (Me.CloseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CloseCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CloseAsync()
            Me.CloseAsync(Nothing)
        End Sub
        
        Public Overloads Sub CloseAsync(ByVal userState As Object)
            If (Me.onBeginCloseDelegate Is Nothing) Then
                Me.onBeginCloseDelegate = AddressOf Me.OnBeginClose
            End If
            If (Me.onEndCloseDelegate Is Nothing) Then
                Me.onEndCloseDelegate = AddressOf Me.OnEndClose
            End If
            If (Me.onCloseCompletedDelegate Is Nothing) Then
                Me.onCloseCompletedDelegate = AddressOf Me.OnCloseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCloseDelegate, Nothing, Me.onEndCloseDelegate, Me.onCloseCompletedDelegate, userState)
        End Sub
        
        Protected Overrides Function CreateChannel() As KniffelGameService.DuplexService
            Return New DuplexServiceClientChannel(Me)
        End Function
        
        Private Class DuplexServiceClientCallback
            Inherits Object
            Implements DuplexServiceCallback
            
            Private proxy As DuplexServiceClient
            
            Public Sub Initialize(ByVal proxy As DuplexServiceClient)
                Me.proxy = proxy
            End Sub
            
            Public Sub SendToClient(ByVal request As KniffelGameService.SendToClient) Implements DuplexServiceCallback.SendToClient
                Me.proxy.OnSendToClientReceived(New Object() {request})
            End Sub
        End Class
        
        Private Class DuplexServiceClientChannel
            Inherits ChannelBase(Of KniffelGameService.DuplexService)
            Implements KniffelGameService.DuplexService
            
            Public Sub New(ByVal client As System.ServiceModel.DuplexClientBase(Of KniffelGameService.DuplexService))
                MyBase.New(client)
            End Sub
            
            Public Function BeginSendToService(ByVal request As KniffelGameService.SendToService, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelGameService.DuplexService.BeginSendToService
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("SendToService", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Sub EndSendToService(ByVal result As System.IAsyncResult) Implements KniffelGameService.DuplexService.EndSendToService
                Dim _args((0) - 1) As Object
                MyBase.EndInvoke("SendToService", _args, result)
            End Sub
        End Class
    End Class
    
    Public Class SendToClientReceivedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property request() As KniffelGameService.SendToClient
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),KniffelGameService.SendToClient)
            End Get
        End Property
    End Class
End Namespace
