'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


'
'This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
'
Namespace KniffelPutScore
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.sanet.com/", ConfigurationName:="KniffelPutScore.KniffelServiceSoap")>  _
    Public Interface KniffelServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://www.sanet.com/PutScore", ReplyAction:="*")>  _
        Function BeginPutScore(ByVal request As KniffelPutScore.PutScoreRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndPutScore(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreResponse
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://www.sanet.com/PutScoreIntoTable", ReplyAction:="*")>  _
        Function BeginPutScoreIntoTable(ByVal request As KniffelPutScore.PutScoreIntoTableRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndPutScoreIntoTable(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreIntoTableResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutScoreRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutScore", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.PutScoreRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.PutScoreRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class PutScoreRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Pass As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Score As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserName As String, ByVal Pass As String, ByVal Score As String)
            MyBase.New
            Me.UserName = UserName
            Me.Pass = Pass
            Me.Score = Score
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutScoreResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutScoreResponse", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.PutScoreResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.PutScoreResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class PutScoreResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public PutScoreResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PutScoreResult As Boolean)
            MyBase.New
            Me.PutScoreResult = PutScoreResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutScoreIntoTableRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutScoreIntoTable", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.PutScoreIntoTableRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.PutScoreIntoTableRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class PutScoreIntoTableRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UserName As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Pass As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Score As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public table As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal table As String)
            MyBase.New
            Me.UserName = UserName
            Me.Pass = Pass
            Me.Score = Score
            Me.table = table
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class PutScoreIntoTableResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="PutScoreIntoTableResponse", [Namespace]:="http://www.sanet.com/", Order:=0)>  _
        Public Body As KniffelPutScore.PutScoreIntoTableResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As KniffelPutScore.PutScoreIntoTableResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://www.sanet.com/")>  _
    Partial Public Class PutScoreIntoTableResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public PutScoreIntoTableResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PutScoreIntoTableResult As Boolean)
            MyBase.New
            Me.PutScoreIntoTableResult = PutScoreIntoTableResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface KniffelServiceSoapChannel
        Inherits KniffelPutScore.KniffelServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PutScoreCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PutScoreIntoTableCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Boolean
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class KniffelServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of KniffelPutScore.KniffelServiceSoap)
        Implements KniffelPutScore.KniffelServiceSoap
        
        Private onBeginPutScoreDelegate As BeginOperationDelegate
        
        Private onEndPutScoreDelegate As EndOperationDelegate
        
        Private onPutScoreCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginPutScoreIntoTableDelegate As BeginOperationDelegate
        
        Private onEndPutScoreIntoTableDelegate As EndOperationDelegate
        
        Private onPutScoreIntoTableCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginOpenDelegate As BeginOperationDelegate
        
        Private onEndOpenDelegate As EndOperationDelegate
        
        Private onOpenCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginCloseDelegate As BeginOperationDelegate
        
        Private onEndCloseDelegate As EndOperationDelegate
        
        Private onCloseCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Property CookieContainer() As System.Net.CookieContainer
            Get
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    Return httpCookieContainerManager.CookieContainer
                Else
                    Return Nothing
                End If
            End Get
            Set
                Dim httpCookieContainerManager As System.ServiceModel.Channels.IHttpCookieContainerManager = Me.InnerChannel.GetProperty(Of System.ServiceModel.Channels.IHttpCookieContainerManager)
                If (Not (httpCookieContainerManager) Is Nothing) Then
                    httpCookieContainerManager.CookieContainer = value
                Else
                    Throw New System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC"& _ 
                            "ookieContainerBindingElement.")
                End If
            End Set
        End Property
        
        Public Event PutScoreCompleted As System.EventHandler(Of PutScoreCompletedEventArgs)
        
        Public Event PutScoreIntoTableCompleted As System.EventHandler(Of PutScoreIntoTableCompletedEventArgs)
        
        Public Event OpenCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        Public Event CloseCompleted As System.EventHandler(Of System.ComponentModel.AsyncCompletedEventArgs)
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_BeginPutScore(ByVal request As KniffelPutScore.PutScoreRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginPutScore
            Return MyBase.Channel.BeginPutScore(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginPutScore(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As KniffelPutScore.PutScoreRequest = New KniffelPutScore.PutScoreRequest()
            inValue.Body = New KniffelPutScore.PutScoreRequestBody()
            inValue.Body.UserName = UserName
            inValue.Body.Pass = Pass
            inValue.Body.Score = Score
            Return CType(Me,KniffelPutScore.KniffelServiceSoap).BeginPutScore(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_EndPutScore(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreResponse Implements KniffelPutScore.KniffelServiceSoap.EndPutScore
            Return MyBase.Channel.EndPutScore(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndPutScore(ByVal result As System.IAsyncResult) As Boolean
            Dim retVal As KniffelPutScore.PutScoreResponse = CType(Me,KniffelPutScore.KniffelServiceSoap).EndPutScore(result)
            Return retVal.Body.PutScoreResult
        End Function
        
        Private Function OnBeginPutScore(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim UserName As String = CType(inValues(0),String)
            Dim Pass As String = CType(inValues(1),String)
            Dim Score As String = CType(inValues(2),String)
            Return Me.BeginPutScore(UserName, Pass, Score, callback, asyncState)
        End Function
        
        Private Function OnEndPutScore(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Boolean = Me.EndPutScore(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnPutScoreCompleted(ByVal state As Object)
            If (Not (Me.PutScoreCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent PutScoreCompleted(Me, New PutScoreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub PutScoreAsync(ByVal UserName As String, ByVal Pass As String, ByVal Score As String)
            Me.PutScoreAsync(UserName, Pass, Score, Nothing)
        End Sub
        
        Public Overloads Sub PutScoreAsync(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal userState As Object)
            If (Me.onBeginPutScoreDelegate Is Nothing) Then
                Me.onBeginPutScoreDelegate = AddressOf Me.OnBeginPutScore
            End If
            If (Me.onEndPutScoreDelegate Is Nothing) Then
                Me.onEndPutScoreDelegate = AddressOf Me.OnEndPutScore
            End If
            If (Me.onPutScoreCompletedDelegate Is Nothing) Then
                Me.onPutScoreCompletedDelegate = AddressOf Me.OnPutScoreCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginPutScoreDelegate, New Object() {UserName, Pass, Score}, Me.onEndPutScoreDelegate, Me.onPutScoreCompletedDelegate, userState)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_BeginPutScoreIntoTable(ByVal request As KniffelPutScore.PutScoreIntoTableRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginPutScoreIntoTable
            Return MyBase.Channel.BeginPutScoreIntoTable(request, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function BeginPutScoreIntoTable(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal table As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim inValue As KniffelPutScore.PutScoreIntoTableRequest = New KniffelPutScore.PutScoreIntoTableRequest()
            inValue.Body = New KniffelPutScore.PutScoreIntoTableRequestBody()
            inValue.Body.UserName = UserName
            inValue.Body.Pass = Pass
            inValue.Body.Score = Score
            inValue.Body.table = table
            Return CType(Me,KniffelPutScore.KniffelServiceSoap).BeginPutScoreIntoTable(inValue, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function KniffelPutScore_KniffelServiceSoap_EndPutScoreIntoTable(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreIntoTableResponse Implements KniffelPutScore.KniffelServiceSoap.EndPutScoreIntoTable
            Return MyBase.Channel.EndPutScoreIntoTable(result)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Private Function EndPutScoreIntoTable(ByVal result As System.IAsyncResult) As Boolean
            Dim retVal As KniffelPutScore.PutScoreIntoTableResponse = CType(Me,KniffelPutScore.KniffelServiceSoap).EndPutScoreIntoTable(result)
            Return retVal.Body.PutScoreIntoTableResult
        End Function
        
        Private Function OnBeginPutScoreIntoTable(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim UserName As String = CType(inValues(0),String)
            Dim Pass As String = CType(inValues(1),String)
            Dim Score As String = CType(inValues(2),String)
            Dim table As String = CType(inValues(3),String)
            Return Me.BeginPutScoreIntoTable(UserName, Pass, Score, table, callback, asyncState)
        End Function
        
        Private Function OnEndPutScoreIntoTable(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Boolean = Me.EndPutScoreIntoTable(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnPutScoreIntoTableCompleted(ByVal state As Object)
            If (Not (Me.PutScoreIntoTableCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent PutScoreIntoTableCompleted(Me, New PutScoreIntoTableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub PutScoreIntoTableAsync(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal table As String)
            Me.PutScoreIntoTableAsync(UserName, Pass, Score, table, Nothing)
        End Sub
        
        Public Overloads Sub PutScoreIntoTableAsync(ByVal UserName As String, ByVal Pass As String, ByVal Score As String, ByVal table As String, ByVal userState As Object)
            If (Me.onBeginPutScoreIntoTableDelegate Is Nothing) Then
                Me.onBeginPutScoreIntoTableDelegate = AddressOf Me.OnBeginPutScoreIntoTable
            End If
            If (Me.onEndPutScoreIntoTableDelegate Is Nothing) Then
                Me.onEndPutScoreIntoTableDelegate = AddressOf Me.OnEndPutScoreIntoTable
            End If
            If (Me.onPutScoreIntoTableCompletedDelegate Is Nothing) Then
                Me.onPutScoreIntoTableCompletedDelegate = AddressOf Me.OnPutScoreIntoTableCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginPutScoreIntoTableDelegate, New Object() {UserName, Pass, Score, table}, Me.onEndPutScoreIntoTableDelegate, Me.onPutScoreIntoTableCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginOpen(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginOpen(callback, asyncState)
        End Function
        
        Private Function OnEndOpen(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndOpen(result)
            Return Nothing
        End Function
        
        Private Sub OnOpenCompleted(ByVal state As Object)
            If (Not (Me.OpenCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent OpenCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub OpenAsync()
            Me.OpenAsync(Nothing)
        End Sub
        
        Public Overloads Sub OpenAsync(ByVal userState As Object)
            If (Me.onBeginOpenDelegate Is Nothing) Then
                Me.onBeginOpenDelegate = AddressOf Me.OnBeginOpen
            End If
            If (Me.onEndOpenDelegate Is Nothing) Then
                Me.onEndOpenDelegate = AddressOf Me.OnEndOpen
            End If
            If (Me.onOpenCompletedDelegate Is Nothing) Then
                Me.onOpenCompletedDelegate = AddressOf Me.OnOpenCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginOpenDelegate, Nothing, Me.onEndOpenDelegate, Me.onOpenCompletedDelegate, userState)
        End Sub
        
        Private Function OnBeginClose(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return CType(Me,System.ServiceModel.ICommunicationObject).BeginClose(callback, asyncState)
        End Function
        
        Private Function OnEndClose(ByVal result As System.IAsyncResult) As Object()
            CType(Me,System.ServiceModel.ICommunicationObject).EndClose(result)
            Return Nothing
        End Function
        
        Private Sub OnCloseCompleted(ByVal state As Object)
            If (Not (Me.CloseCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent CloseCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(e.[Error], e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub CloseAsync()
            Me.CloseAsync(Nothing)
        End Sub
        
        Public Overloads Sub CloseAsync(ByVal userState As Object)
            If (Me.onBeginCloseDelegate Is Nothing) Then
                Me.onBeginCloseDelegate = AddressOf Me.OnBeginClose
            End If
            If (Me.onEndCloseDelegate Is Nothing) Then
                Me.onEndCloseDelegate = AddressOf Me.OnEndClose
            End If
            If (Me.onCloseCompletedDelegate Is Nothing) Then
                Me.onCloseCompletedDelegate = AddressOf Me.OnCloseCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginCloseDelegate, Nothing, Me.onEndCloseDelegate, Me.onCloseCompletedDelegate, userState)
        End Sub
        
        Protected Overrides Function CreateChannel() As KniffelPutScore.KniffelServiceSoap
            Return New KniffelServiceSoapClientChannel(Me)
        End Function
        
        Private Class KniffelServiceSoapClientChannel
            Inherits ChannelBase(Of KniffelPutScore.KniffelServiceSoap)
            Implements KniffelPutScore.KniffelServiceSoap
            
            Public Sub New(ByVal client As System.ServiceModel.ClientBase(Of KniffelPutScore.KniffelServiceSoap))
                MyBase.New(client)
            End Sub
            
            Public Function BeginPutScore(ByVal request As KniffelPutScore.PutScoreRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginPutScore
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("PutScore", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndPutScore(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreResponse Implements KniffelPutScore.KniffelServiceSoap.EndPutScore
                Dim _args((0) - 1) As Object
                Dim _result As KniffelPutScore.PutScoreResponse = CType(MyBase.EndInvoke("PutScore", _args, result),KniffelPutScore.PutScoreResponse)
                Return _result
            End Function
            
            Public Function BeginPutScoreIntoTable(ByVal request As KniffelPutScore.PutScoreIntoTableRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements KniffelPutScore.KniffelServiceSoap.BeginPutScoreIntoTable
                Dim _args((1) - 1) As Object
                _args(0) = request
                Dim _result As System.IAsyncResult = MyBase.BeginInvoke("PutScoreIntoTable", _args, callback, asyncState)
                Return _result
            End Function
            
            Public Function EndPutScoreIntoTable(ByVal result As System.IAsyncResult) As KniffelPutScore.PutScoreIntoTableResponse Implements KniffelPutScore.KniffelServiceSoap.EndPutScoreIntoTable
                Dim _args((0) - 1) As Object
                Dim _result As KniffelPutScore.PutScoreIntoTableResponse = CType(MyBase.EndInvoke("PutScoreIntoTable", _args, result),KniffelPutScore.PutScoreIntoTableResponse)
                Return _result
            End Function
        End Class
    End Class
End Namespace
